# Generated by Django 6.0.6 on 2026-09-14 13:14

import apps.data_permission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPermissionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.data_permission.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('dimension_type', models.CharField(choices=[('ROLE', '角色'), ('DEPARTMENT', '部门'), ('USER', '用户')], max_length=16, verbose_name='维度类型')),
                ('dimension_value', models.CharField(help_text='ROLE→role_code / DEPARTMENT→department_id / USER→user_id', max_length=64, verbose_name='维度值')),
                ('level', models.CharField(choices=[('ROW', '行级'), ('COLUMN', '列级')], max_length=8, verbose_name='规则层级')),
                ('scope_type', models.CharField(blank=True, choices=[('ALL', '全部数据'), ('DEPT', '仅本部门'), ('DEPT_AND_SUB', '本部门及下属'), ('SELF', '仅自己创建'), ('CUSTOM', '自定义范围')], max_length=16, null=True, verbose_name='行级范围类型')),
                ('scope_payload', models.JSONField(blank=True, help_text='scope_type=CUSTOM 时生效: {"department_ids":[...]} 或 {"management_unit_ids":[...]}', null=True, verbose_name='行级自定义范围')),
                ('entity', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='实体')),
                ('field', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='字段')),
                ('permission', models.CharField(blank=True, choices=[('READ', '可读'), ('MASK', '脱敏'), ('NONE', '不可见')], max_length=8, null=True, verbose_name='列级权限')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级(大者优先)')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态(1启用 0停用)')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('created_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建人ID')),
            ],
            options={
                'verbose_name': '数据权限规则',
                'verbose_name_plural': '数据权限规则',
                'db_table': 'data_permission_rules',
                'indexes': [models.Index(fields=['dimension_type', 'dimension_value'], name='idx_dp_dim'), models.Index(fields=['level'], name='idx_dp_level')],
            },
        ),
    ]
