# Generated by Django 6.0.6 on 2026-09-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapermissionrule',
            name='scope_type',
            field=models.CharField(blank=True, choices=[('ALL', '全部数据'), ('NONE', '无数据'), ('DEPT', '仅本部门'), ('DEPT_AND_SUB', '本部门及下属'), ('SELF', '仅自己创建'), ('CUSTOM', '自定义范围')], max_length=16, null=True, verbose_name='行级范围类型'),
        ),
    ]
