# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.automation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.automation.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(db_index=True, max_length=32, verbose_name='候选人ID')),
                ('trigger_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='触发时间')),
                ('evaluate_result', models.CharField(choices=[('MATCHED', '匹配'), ('UNMATCHED', '不匹配'), ('ERROR', '错误')], max_length=16, verbose_name='评估结果')),
                ('action_taken', models.CharField(blank=True, max_length=200, verbose_name='实际执行动作')),
                ('skip_reason', models.CharField(blank=True, max_length=500, verbose_name='跳过原因')),
                ('error_message', models.TextField(blank=True, verbose_name='异常信息')),
                ('execution_ms', models.IntegerField(blank=True, null=True, verbose_name='执行耗时（ms）')),
            ],
            options={
                'verbose_name': '自动化执行日志',
                'verbose_name_plural': '自动化执行日志',
                'db_table': 'automation_logs',
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.automation.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='规则名称')),
                ('trigger_type', models.CharField(choices=[('STAGE_ENTERED', '进入阶段'), ('STATE_CHANGED', '状态变更'), ('EVALUATION_SUBMITTED', '评价提交'), ('SCHEDULED', '定时巡检')], max_length=32, verbose_name='触发器')),
                ('trigger_timing', models.CharField(choices=[('IMMEDIATE', '立即执行'), ('DELAY', '延迟 N 小时'), ('WORKING_DAYS', '1-15 个工作日')], max_length=32, verbose_name='执行时机')),
                ('trigger_delay_hours', models.IntegerField(blank=True, null=True, verbose_name='延迟小时数')),
                ('condition_logic', models.CharField(choices=[('ALL', '全部满足'), ('ANY', '任意满足')], default='ALL', max_length=8, verbose_name='条件逻辑')),
                ('condition_json', models.JSONField(default=list, verbose_name='子规则')),
                ('action_type', models.CharField(choices=[('AUTO_ADVANCE', '自动推进到下一阶段'), ('SKIP_TO', '跳过到指定阶段'), ('REMIND', '发提醒'), ('REJECT_TO_POOL', '入公共人才库')], max_length=32, verbose_name='动作类型')),
                ('skip_check', models.BooleanField(default=False, verbose_name='无视下阶段进入条件')),
                ('scope_json', models.JSONField(default=dict, help_text='{positions, priority, referral_type}', verbose_name='适用范围')),
                ('priority', models.CharField(choices=[('P0', 'P0 - 最高'), ('P1', 'P1 - 中'), ('P2', 'P2 - 低')], default='P1', max_length=8, verbose_name='优先级')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('failure_rate_threshold', models.FloatField(default=0.5, verbose_name='熔断失败率阈值')),
            ],
            options={
                'verbose_name': '自动化规则',
                'verbose_name_plural': '自动化规则',
                'db_table': 'automation_rules',
            },
        ),
    ]
