# Generated by Django 5.0.6 on 2026-06-16 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='next_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='process.recruitmentstage', verbose_name='目标阶段'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='process.recruitmentprocess', verbose_name='所属流程'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='process.recruitmentstage', verbose_name='触发现阶段'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='automationlog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.automationrule', verbose_name='规则'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['process', 'stage'], name='automation__process_e0381f_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['enabled', 'priority'], name='automation__enabled_7004d2_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['rule', 'trigger_time'], name='automation__rule_id_714030_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['candidate_id'], name='automation__candida_a900b9_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['evaluate_result', 'trigger_time'], name='automation__evaluat_93d6e5_idx'),
        ),
    ]
