# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.invitation.models
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0002_application_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.invitation.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='邀约时间')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('expire_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_grab_pool', models.BooleanField(default=False, verbose_name='抢单池')),
                ('grabbed_at', models.DateTimeField(blank=True, null=True, verbose_name='抢单时间')),
                ('candidate_response', models.CharField(blank=True, help_text='AGREE/REJECT/CALLBACK/NO_RESPONSE', max_length=32, verbose_name='候选人响应')),
                ('candidate_note', models.TextField(blank=True, verbose_name='候选人备注')),
                ('state', django_fsm.FSMField(db_index=True, default='PENDING', max_length=50, protected=True, verbose_name='邀约状态')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='application.application', verbose_name='申请')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('grabbed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='抢单人')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='邀约人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '邀约',
                'verbose_name_plural': '邀约',
                'db_table': 'invitations',
                'indexes': [models.Index(fields=['state', 'expire_at'], name='invitations_state_82b165_idx'), models.Index(fields=['is_grab_pool', 'state'], name='invitations_is_grab_b6ba29_idx')],
            },
        ),
    ]
