# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.application.models
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.application.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='申请编号')),
                ('workflow_version', models.CharField(help_text='创建时的版本（冻结）', max_length=20, verbose_name='流程版本')),
                ('state', django_fsm.FSMField(db_index=True, default='PENDING', max_length=50, protected=True, verbose_name='申请状态')),
                ('time_limit_rule_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='匹配的限时规则ID')),
                ('total_time_limit_days', models.IntegerField(blank=True, null=True, verbose_name='总限时天数')),
                ('stage_entered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='当前阶段进入时间')),
                ('stage_deadline', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='阶段截止时间')),
                ('is_grabbed', models.BooleanField(default=False, verbose_name='是否已被认领')),
                ('grabbed_at', models.DateTimeField(blank=True, null=True, verbose_name='认领时间')),
                ('last_advanced_at', models.DateTimeField(blank=True, null=True, verbose_name='最后推进时间')),
            ],
            options={
                'verbose_name': '申请',
                'verbose_name_plural': '申请',
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.application.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', '创建'), ('ADVANCED', '推进'), ('REJECTED', '回退'), ('SKIPPED', '跳过'), ('PAUSED', '暂停'), ('RESUMED', '恢复'), ('OFFER_SENT', '发送Offer'), ('GRABBED', '抢单'), ('TIMEOUT', '超时'), ('UPGRADE_VERSION', '升版本'), ('AUTO', '自动操作')], max_length=32, verbose_name='操作类型')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('is_auto', models.BooleanField(default=False, verbose_name='是否自动')),
            ],
            options={
                'verbose_name': '申请操作历史',
                'verbose_name_plural': '申请操作历史',
                'db_table': 'application_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStageRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.application.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('NOT_STARTED', '未开始'), ('PENDING', '待处理'), ('TO_BE_SCHEDULED', '待安排'), ('PROCESSING', '处理中'), ('PASSED', '已通过'), ('FAILED', '未通过'), ('SKIPPED', '已跳过'), ('REJECTED', '已回退'), ('TIMEOUT', '超时'), ('ARCHIVED', '已归档')], db_index=True, default='NOT_STARTED', max_length=20, verbose_name='阶段状态')),
                ('entered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='进入时间')),
                ('exited_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='离开时间')),
                ('duration_days', models.IntegerField(blank=True, null=True, verbose_name='停留时长（天）')),
                ('time_limit_rule_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='匹配限时规则ID')),
                ('total_time_limit_days', models.IntegerField(blank=True, null=True, verbose_name='总限时天数')),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='阶段截止时间')),
                ('current_handlers', models.JSONField(default=list, help_text='list of userId', verbose_name='当前处理人')),
                ('auto_promoted', models.BooleanField(default=False, verbose_name='是否自动推进')),
                ('automation_rule_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='触发的规则ID')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '申请阶段记录',
                'verbose_name_plural': '申请阶段记录',
                'db_table': 'application_stage_records',
                'ordering': ['application', 'entered_at'],
            },
        ),
    ]
