# Generated by Django 5.0.6 on 2026-07-01 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('trigger_event', models.CharField(help_text='如 stage-entered/candidate-added', max_length=50)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MOU 自动化规则',
                'db_table': 'mou_automation_rules',
            },
        ),
        migrations.CreateModel(
            name='MutualExclusionGroup',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('members', models.JSONField(default=list, help_text='互斥的 stage id list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '互斥组',
                'db_table': 'mou_mutual_exclusion_groups',
            },
        ),
        migrations.CreateModel(
            name='MouAgreement',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='MOU 编码, 如 MOU-2026-001', max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('signed_at', models.DateField(blank=True, null=True)),
                ('effective_at', models.DateField(blank=True, null=True)),
                ('expire_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='DRAFT', help_text='DRAFT/ACTIVE/EXPIRED/TERMINATED', max_length=20)),
                ('terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mou_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MOU 协议',
                'db_table': 'mou_agreements',
            },
        ),
        migrations.CreateModel(
            name='MouContainer',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('position_title', models.CharField(max_length=200)),
                ('quota_total', models.IntegerField(default=0)),
                ('quota_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='mou.mouagreement')),
            ],
            options={
                'verbose_name': 'MOU 配额容器',
                'db_table': 'mou_containers',
            },
        ),
    ]
