# Generated by Django 5.0.6 on 2026-07-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouagreement',
            name='description',
            field=models.TextField(blank=True, default='', help_text='描述 (FE 字段, 兼容 terms)'),
        ),
        migrations.AddField(
            model_name='mouagreement',
            name='mou_type',
            field=models.CharField(blank=True, default='STANDARD', help_text='MOU 类型: STANDARD/EXCLUSIVE/PROJECT_BASED', max_length=50),
        ),
        migrations.AddField(
            model_name='mouagreement',
            name='name',
            field=models.CharField(blank=True, default='', help_text='MOU 名称 (FE 字段, 兼容)', max_length=200),
        ),
        migrations.AddField(
            model_name='mouagreement',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='权限范围 list (FE 字段)'),
        ),
        migrations.AlterField(
            model_name='mouagreement',
            name='terms',
            field=models.TextField(blank=True, default='', help_text='MOU 条款'),
        ),
    ]
