# Generated by Django 6.0.6 on 2026-07-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0002_mouagreement_description_mouagreement_mou_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moucontainer',
            name='description',
            field=models.TextField(blank=True, default='', help_text='容器描述'),
        ),
        migrations.AddField(
            model_name='moucontainer',
            name='quota_status',
            field=models.CharField(default='ACTIVE', help_text='ACTIVE/INACTIVE/EXHAUSTED', max_length=20),
        ),
        migrations.AddField(
            model_name='moucontainer',
            name='resource_filter',
            field=models.JSONField(blank=True, default=dict, help_text='资源过滤条件 (JSON)'),
        ),
        migrations.AddField(
            model_name='moucontainer',
            name='type',
            field=models.CharField(blank=True, default='', help_text='容器类型: PROJECT/DEPARTMENT/...', max_length=50),
        ),
    ]
