# Generated by Django 6.0.6 on 2026-09-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0004_rename_automationrule_to_mourule'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouagreement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='moucontainer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='mourule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='mutualexclusiongroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
    ]
