// 独立生成版本模块（供 vue-tsc / 类型检查在 vite 启动前使用）。
// 与 vite.config.ts 的 appVersionPlugin 保持同一份逻辑：写入 src/generated/appVersion.ts。
// 该文件被 .gitignore 忽略（构建/启动期自动生成），因此全新 clone 后必须先跑本脚本，
// 否则 vue-tsc 会因找不到 '@/generated/appVersion' 而报类型错误。
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execSync } from 'node:child_process'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

function resolveAppVersion() {
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
  } catch {
    // 无 git 环境（如 CI 某些场景）→ 退化为构建时间戳
    return new Date().toISOString()
  }
}

const version = resolveAppVersion()
const buildTime = new Date().toISOString()

const dir = path.resolve(root, 'src', 'generated')
fs.mkdirSync(dir, { recursive: true })
fs.writeFileSync(
  path.resolve(dir, 'appVersion.ts'),
  [
    '// AUTO-GENERATED by scripts/gen-version.mjs / vite appVersionPlugin. DO NOT EDIT.',
    `export const APP_VERSION = ${JSON.stringify(version)}`,
    `export const APP_BUILD_TIME = ${JSON.stringify(buildTime)}`,
    '',
  ].join('\n'),
)

console.log(`[gen-version] APP_VERSION=${version} 已写入 src/generated/appVersion.ts`)
