// 版本文件唯一写入器：同时生成 src/generated/appVersion.ts 与 public/version.json。
//
// 🔴 必须成对双写（2026-09-23 弹窗无限弹缺陷的根因修复）：
//    旧版本脚本只写模块、vite 插件只在 dev server / build 启动时写双份。
//    并行会话跑 `npm run typecheck`（前置 gen:version）单独重写了模块，
//    与运行中 dev server 启动时写入的 version.json 失步（025dac0 vs 171d4a1）
//    → 前端「本地版本 vs 线上版本」永久 mismatch → 「系统已升级」弹窗
//    刷新后两文件原样未变 → 无限重复弹出。
//    收敛为唯一写入器后：任何调用方（CLI / vite 插件）重生成，两文件必然同步。
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { execSync } from 'node:child_process'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

export function resolveAppVersion() {
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
  } catch {
    // 无 git 环境（如 CI 某些场景）→ 退化为构建时间戳
    return new Date().toISOString()
  }
}

/** 双写版本文件（版本模块 + 线上 version.json）。任何写入方都不得只写其一。 */
export function writeVersionFiles() {
  const version = resolveAppVersion()
  const buildTime = new Date().toISOString()

  // 1) 版本模块：编译期打进 bundle，作为「本地版本」
  const genDir = path.resolve(root, 'src', 'generated')
  fs.mkdirSync(genDir, { recursive: true })
  fs.writeFileSync(
    path.resolve(genDir, 'appVersion.ts'),
    [
      '// AUTO-GENERATED by scripts/gen-version.mjs / vite appVersionPlugin. DO NOT EDIT.',
      `export const APP_VERSION = ${JSON.stringify(version)}`,
      `export const APP_BUILD_TIME = ${JSON.stringify(buildTime)}`,
      '',
    ].join('\n'),
  )

  // 2) 线上版本源：dev 由 public/ 直出，build 拷到产物根目录，前端轮询比对用
  fs.mkdirSync(path.resolve(root, 'public'), { recursive: true })
  fs.writeFileSync(
    path.resolve(root, 'public', 'version.json'),
    JSON.stringify({ version, buildTime }, null, 2),
  )

  return { version, buildTime }
}

// 仅直接执行（node scripts/gen-version.mjs）时落盘；被 vite.config.ts import 时不重复执行
const isMain =
  process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
if (isMain) {
  const { version } = writeVersionFiles()
  console.log(
    `[gen-version] APP_VERSION=${version} 已双写 src/generated/appVersion.ts + public/version.json`,
  )
}
