# Generated by Django 6.0.6 on 2026-08-04 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0006_alter_candidate_email_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedResume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_url', models.URLField(help_text='原始抓取 URL, 用于排查 + 去重', max_length=1024)),
                ('source_platform', models.CharField(help_text='平台标识 (拉勾/BOSS/智联/...) - Phase 3 改为枚举外键', max_length=64)),
                ('raw_content', models.TextField(help_text='抓回的原始 HTML / 文本, 解析失败时回看')),
                ('parsed_content', models.JSONField(blank=True, default=dict, help_text='结构化解析结果 (姓名/电话/邮箱/工作经历等), JSON 形态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='入库时间 (抓取完成入库点)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='字段最近修改时间')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Phase 3 扩展字段: status(scraper_state) / scraper_job_name / import_error / retry_count 等暂存此处')),
                ('candidate', models.ForeignKey(blank=True, help_text='解析后映射到的候选人 (NULL = 未匹配, 待 T06 落地)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_sources', to='candidate.candidate')),
            ],
            options={
                'verbose_name': '抓取简历 (G30 stub)',
                'verbose_name_plural': '抓取简历 (G30 stub)',
                'db_table': 'scraped_resumes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_platform', '-created_at'], name='idx_scraped_resume_lookup')],
            },
        ),
    ]
