# Generated by Django 6.0.6 on 2026-09-12 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('key', models.CharField(default='merge', max_length=64, unique=True, verbose_name='配置键')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置内容')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '重复候选人配置',
                'verbose_name_plural': '重复候选人配置',
                'db_table': 'dup_configs',
            },
        ),
        migrations.CreateModel(
            name='DuplicateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('scope', models.CharField(choices=[('ALL', '全局'), ('SOCIAL', '社招'), ('CAMPUS', '校招')], default='ALL', max_length=16, verbose_name='适用范围')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统内置')),
                ('condition_logic', models.CharField(choices=[('ALL', '全部一致'), ('ANY', '任意 N 项一致')], default='ALL', max_length=8, verbose_name='查重条件')),
                ('any_count', models.PositiveSmallIntegerField(default=1, verbose_name='任意一致项数')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='查重项')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '候选人查重规则',
                'verbose_name_plural': '候选人查重规则',
                'db_table': 'dup_rules',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
