# Generated by Django 6.0.6 on 2026-08-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidate_id_card_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='邮箱 hash (sha256, 用于查重/匿名查询)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, help_text='hash_for_search(phone) 写入, 同明文 → 同 hash', max_length=64, verbose_name='手机号 hash (sha256, 用于查重/匿名查询)'),
        ),
    ]
