# Generated by Django 6.0.6 on 2026-08-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_alter_candidate_email_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='major_tag',
            field=models.CharField(blank=True, choices=[('工学', '工学'), ('其他', '其他')], default='', max_length=16, verbose_name='专业标签'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='school_tag',
            field=models.CharField(blank=True, choices=[('985', '985'), ('211', '211'), ('双一流', '双一流'), ('其他', '其他')], default='', max_length=16, verbose_name='院校标签'),
        ),
    ]
