# Generated by Django 6.0.6 on 2026-09-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidate_major_tag_candidate_school_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
    ]
