# Generated by Django 6.0.6 on 2026-09-10 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_candidatetag_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('field_key', models.CharField(max_length=128, verbose_name='字段 Key')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='字段值')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='candidate.candidate', verbose_name='候选人')),
            ],
            options={
                'verbose_name': '候选人字段值',
                'verbose_name_plural': '候选人字段值',
                'db_table': 'candidate_field_values',
                'ordering': ['field_key'],
                'unique_together': {('candidate', 'field_key')},
            },
        ),
    ]
