# Generated by Django 6.0.6 on 2026-09-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_candidate_recruit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='邮箱 hash (sha256, 用于查重/匿名查询)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id_card_hash',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='身份证号 hash (sha256, 用于查重/匿名查询)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, help_text='hash_for_search(phone) 写入, 同明文 → 同 hash', max_length=80, verbose_name='手机号 hash (sha256, 用于查重/匿名查询)'),
        ),
    ]
