# Generated by Django 6.0.6 on 2026-09-28 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.candidate.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_widen_pii_hash_columns'),
        ('position', '0004_position_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否归档'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruited_candidates', to=settings.AUTH_USER_MODEL, verbose_name='招聘官'),
        ),
        migrations.CreateModel(
            name='CandidatePositionRecommendation',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.candidate.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, verbose_name='推荐理由')),
                ('recruit_type', models.CharField(choices=[('social', 'social'), ('campus', 'campus')], db_index=True, default='social', max_length=16, verbose_name='招聘类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='推荐时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_recommendations', to='candidate.candidate', verbose_name='候选人')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_recommendations', to='position.position', verbose_name='推荐职位')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='推荐人')),
            ],
            options={
                'verbose_name': '候选人职位推荐记录',
                'verbose_name_plural': '候选人职位推荐记录',
                'db_table': 'candidate_position_recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'position'], name='candidate_p_candida_53b105_idx'), models.Index(fields=['recommender', 'created_at'], name='candidate_p_recomme_5542bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateScreening',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.candidate.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('PASS', '通过'), ('FAIL', '不通过'), ('KEEP', '待议')], default='PASS', max_length=16, verbose_name='初筛结果')),
                ('comment', models.TextField(blank=True, verbose_name='初筛备注')),
                ('recruit_type', models.CharField(choices=[('social', 'social'), ('campus', 'campus')], db_index=True, default='social', max_length=16, verbose_name='招聘类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='初筛时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_records', to='candidate.candidate', verbose_name='候选人')),
                ('screener', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_screenings', to=settings.AUTH_USER_MODEL, verbose_name='初筛人')),
            ],
            options={
                'verbose_name': '候选人初筛记录',
                'verbose_name_plural': '候选人初筛记录',
                'db_table': 'candidate_screenings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'result'], name='candidate_s_candida_5187e3_idx'), models.Index(fields=['screener', 'created_at'], name='candidate_s_screene_2e7680_idx')],
            },
        ),
    ]
