# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.process.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.process.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板编码')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('category', models.CharField(help_text='SOCIAL/CAMPUS/HEADHUNTER/INTERNAL/CUSTOM', max_length=50, verbose_name='分类')),
                ('snapshot', models.JSONField(default=dict, help_text='包含 stages + rules + scope', verbose_name='流程快照')),
                ('is_builtin', models.BooleanField(db_index=True, default=False, verbose_name='预置')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '流程模板',
                'verbose_name_plural': '流程模板',
                'db_table': 'process_templates',
                'ordering': ['-is_builtin', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentProcess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.process.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='W+三位流水号', max_length=20, unique=True, verbose_name='流程编号')),
                ('name', models.CharField(help_text='限 30 字，不可重复', max_length=30, verbose_name='流程名称')),
                ('current_version', models.CharField(default='1.0', help_text='如 V1.2', max_length=20, verbose_name='当前版本')),
                ('applicable_scope', models.JSONField(blank=True, default=dict, help_text='{"items": [...conditions], "expression": "(1 AND 2) OR 3"}', verbose_name='适用范围')),
                ('is_template', models.BooleanField(db_index=True, default=False, verbose_name='是否模板')),
                ('template_code', models.CharField(blank=True, db_index=True, help_text='SOCIAL_TECH / CAMPUS_GENERAL / HEADHUNTER_SENIOR / INTERNAL_TRANSFER', max_length=50, null=True, verbose_name='模板编码')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('validate_resume_score', models.BooleanField(default=True, verbose_name='校验简历评分')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='描述')),
                ('status', models.CharField(choices=[('ENABLED', '启用'), ('ARCHIVED', '已归档')], db_index=True, default='ENABLED', max_length=16, verbose_name='状态')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '招聘流程',
                'verbose_name_plural': '招聘流程',
                'db_table': 'recruitment_processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentStage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.process.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='P+三位流水号', max_length=20, unique=True, verbose_name='阶段编号')),
                ('name', models.CharField(help_text='限 20 字，不可重复', max_length=20, unique=True, verbose_name='阶段名称')),
                ('stage_type', models.CharField(choices=[('SCREEN', '筛选型'), ('INVITATION', '邀约型'), ('INTERVIEW', '面试型'), ('OFFER', 'Offer型')], max_length=20, verbose_name='阶段类型')),
                ('status', models.CharField(choices=[('ENABLED', '启用'), ('DISABLED', '停用')], db_index=True, default='ENABLED', max_length=16, verbose_name='状态')),
                ('is_builtin', models.BooleanField(db_index=True, default=False, verbose_name='预置阶段')),
                ('default_features', models.JSONField(default=list, verbose_name='默认功能')),
                ('optional_features', models.JSONField(default=list, verbose_name='可选功能')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='描述')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '阶段',
                'verbose_name_plural': '阶段',
                'db_table': 'recruitment_stages',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStageLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.process.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='顺序')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必经')),
                ('entry_rule_expression', models.CharField(blank=True, help_text='如 (1 AND 2) OR (3 AND 4)', max_length=500, verbose_name='全局规则表达式')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_links', to='process.recruitmentprocess', verbose_name='所属流程')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_stage_links', to='process.recruitmentstage', verbose_name='阶段')),
            ],
            options={
                'verbose_name': '流程-阶段关联',
                'verbose_name_plural': '流程-阶段关联',
                'db_table': 'process_stage_links',
                'ordering': ['process', 'order'],
                'unique_together': {('process', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='StageRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.process.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('data_source', models.CharField(blank=True, help_text='DEMAND / POSITION / NONE', max_length=32, verbose_name='数据来源')),
                ('data_field', models.CharField(blank=True, help_text='如 hiring_manager / position_owner', max_length=64, verbose_name='取值字段')),
                ('processing_rule', models.CharField(choices=[('DIRECT', '直接分配（默认）'), ('SEQUENTIAL', '按页面展示顺序执行'), ('ROUND_ROBIN', '邀约阶段轮流邀约制'), ('NONE', '无特定规则')], default='DIRECT', max_length=32, verbose_name='处理规则')),
                ('processor_order', models.JSONField(blank=True, default=list, help_text='SEQUENTIAL 模式下使用，array of userId', verbose_name='处理人顺序列表')),
                ('current_processor_index', models.IntegerField(default=0, verbose_name='当前处理人索引')),
                ('auto_skip_n_plus_two', models.BooleanField(default=False, verbose_name='N+2 推荐免筛选')),
                ('inherit_prior_consensus', models.BooleanField(default=False, verbose_name='引用前序双 A 意见')),
                ('legacy_time_limit_days', models.IntegerField(blank=True, null=True, verbose_name='(已废弃)阶段限时天数')),
                ('legacy_grab_threshold', models.IntegerField(blank=True, null=True, verbose_name='(已废弃)抢单阈值')),
                ('is_grab_mode', models.BooleanField(default=False, verbose_name='抢单模式')),
                ('grab_threshold', models.IntegerField(default=30, verbose_name='抢单阈值')),
                ('interview_rounds', models.IntegerField(default=1, verbose_name='面试轮次')),
                ('interview_format', models.CharField(blank=True, help_text='SINGLE/JOINT/COMPREHENSIVE', max_length=32, verbose_name='面试形式')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_rule', to='process.processstagelink', verbose_name='流程-阶段关联')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '阶段规则',
                'verbose_name_plural': '阶段规则',
                'db_table': 'stage_rules',
            },
        ),
    ]
