# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.analytics.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='导出名称')),
                ('entity', models.CharField(max_length=64, verbose_name='导出实体')),
                ('filters', models.JSONField(default=dict, verbose_name='过滤条件')),
                ('fields', models.JSONField(default=list, verbose_name='导出字段')),
                ('format', models.CharField(choices=[('XLSX', 'Excel'), ('CSV', 'CSV'), ('PDF', 'PDF')], default='XLSX', max_length=8, verbose_name='格式')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=16, verbose_name='状态')),
                ('file_url', models.URLField(blank=True, max_length=500, verbose_name='文件URL')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('row_count', models.IntegerField(blank=True, null=True, verbose_name='行数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '导出任务',
                'verbose_name_plural': '导出任务',
                'db_table': 'export_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.analytics.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='报表名')),
                ('report_type', models.CharField(choices=[('FUNNEL', '漏斗报表'), ('DASHBOARD', 'HR个人看板'), ('CHANNEL_ROI', '渠道ROI'), ('CUSTOM', '自定义')], max_length=32, verbose_name='报表类型')),
                ('scope', models.JSONField(default=dict, help_text='{department, time_range, hr_id, ...}', verbose_name='报表范围')),
                ('data', models.JSONField(default=dict, verbose_name='报表数据')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '报表快照',
                'verbose_name_plural': '报表快照',
                'db_table': 'report_snapshots',
                'ordering': ['-generated_at'],
            },
        ),
    ]
