# Generated by Django 6.0.6 on 2026-08-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_alter_demand_process_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='demand_type',
            field=models.CharField(choices=[('SOCIAL', '社会招聘'), ('CAMPUS', '校园招聘')], default='SOCIAL', max_length=10, verbose_name='需求类型'),
        ),
    ]
