# Generated by Django 6.0.6 on 2026-08-13 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('SYSTEM', '制度'), ('NOTICE', '公告'), ('PROCESS', '流程')], default='SYSTEM', max_length=16, verbose_name='分类')),
                ('audience', models.CharField(choices=[('RECRUIT_EXPERT', '招聘专家'), ('ALL', '全员')], default='RECRUIT_EXPERT', max_length=16, verbose_name='受众')),
                ('body', models.TextField(verbose_name='正文')),
                ('pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '制度公告',
                'verbose_name_plural': '制度公告',
                'ordering': ['-pinned', '-published_at'],
            },
        ),
    ]
