# Generated by Django 6.0.6 on 2026-08-14 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_summary_announcementconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPushRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='推送人数')),
                ('channel', models.CharField(choices=[('IN_APP', '站内信'), ('WECOM', '企微')], default='IN_APP', max_length=16, verbose_name='推送通道')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_records', to='announcement.announcement', verbose_name='所属公告')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('pushed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='推送人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '公告推送记录',
                'verbose_name_plural': '公告推送记录',
                'db_table': 'announcement_push_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
