# Generated by Django 6.0.6 on 2026-08-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_announcementpushrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementconfig',
            name='show_in_more',
            field=models.BooleanField(default=False, verbose_name='更多中展示'),
        ),
    ]
