# Generated by Django 6.0.6 on 2026-08-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_announcementconfig_show_in_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementconfig',
            name='show_in_more',
        ),
        migrations.AddField(
            model_name='announcement',
            name='show_in_more',
            field=models.BooleanField(default=False, verbose_name='更多中展示'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='show_on_workbench',
            field=models.BooleanField(default=True, verbose_name='工作台展示'),
        ),
    ]
