# Generated by Django 5.0.6 on 2026-06-24 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('processing', '处理中'), ('done', '完成'), ('failed', '失败')], default='processing', max_length=16)),
                ('phase', models.CharField(blank=True, choices=[('uploading', '上传中'), ('parsing', '解析中'), ('checking', '查重中')], max_length=16, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('file_size', models.IntegerField()),
                ('error', models.CharField(blank=True, max_length=64, null=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('duplicate_data', models.JSONField(blank=True, null=True)),
                ('draft_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'add_candidate_parsejob',
                'ordering': ['-created_at'],
            },
        ),
    ]
