# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.referral.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0002_candidate_extra'),
        ('position', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.referral.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('referral_type', models.CharField(choices=[('N+1', 'N+1 推荐（直接下属推荐）'), ('N+2', 'N+2 推荐（隔级下属推荐）'), ('INTERNAL', '内部推荐'), ('SOCIAL', '社会推荐')], db_index=True, max_length=8, verbose_name='推荐类型')),
                ('detected_type', models.CharField(blank=True, help_text='系统自动检测的推荐类型', max_length=8, verbose_name='自动检测类型')),
                ('detection_detail', models.JSONField(default=dict, verbose_name='检测详情')),
                ('status', models.CharField(choices=[('SUBMITTED', '已提交'), ('PROCESSING', '处理中'), ('HIRED', '已入职'), ('FAILED', '未通过'), ('WITHDRAWN', '已撤回')], db_index=True, default='SUBMITTED', max_length=16, verbose_name='状态')),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='奖金金额')),
                ('bonus_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='奖金发放时间')),
                ('note', models.TextField(blank=True, verbose_name='推荐理由')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='candidate.candidate', verbose_name='候选人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='position.position', verbose_name='推荐职位')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='推荐人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '推荐记录',
                'verbose_name_plural': '推荐记录',
                'db_table': 'referrals',
                'indexes': [models.Index(fields=['referrer', 'status'], name='referrals_referre_cefb5c_idx'), models.Index(fields=['referral_type', 'status'], name='referrals_referra_9458a6_idx')],
            },
        ),
    ]
