# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.offer.models
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0003_add_user_fks'),
        ('candidate', '0002_candidate_extra'),
        ('position', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.offer.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Offer编号')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='薪资')),
                ('salary_currency', models.CharField(default='CNY', max_length=8, verbose_name='币种')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='职级')),
                ('position_title', models.CharField(blank=True, max_length=100, verbose_name='职务')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='预计入职日期')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Offer过期日期')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='候选人响应时间')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('state', django_fsm.FSMField(db_index=True, default='DRAFT', max_length=50, protected=True, verbose_name='Offer状态')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='application.application', verbose_name='申请')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='candidate.candidate', verbose_name='候选人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='position.position', verbose_name='职位')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offer',
                'db_table': 'offers',
                'indexes': [models.Index(fields=['state', 'created_at'], name='offers_state_5e4d22_idx'), models.Index(fields=['candidate', 'state'], name='offers_candida_e06c1d_idx')],
            },
        ),
    ]
