# Generated by Django 5.0.6 on 2026-06-16 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0002_application_extra'),
        ('position', '0001_initial'),
        ('process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='process.processstagelink', verbose_name='当前阶段关联'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='process.recruitmentstage', verbose_name='当前阶段'),
        ),
        migrations.AddField(
            model_name='application',
            name='grabbed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='认领人'),
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='position.position', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='application',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='process.recruitmentprocess', verbose_name='使用的流程'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='applicationhistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='application.application', verbose_name='申请'),
        ),
        migrations.AddField(
            model_name='applicationhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='applicationhistory',
            name='from_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='process.recruitmentstage', verbose_name='来源阶段'),
        ),
        migrations.AddField(
            model_name='applicationhistory',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='applicationhistory',
            name='to_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='process.recruitmentstage', verbose_name='目标阶段'),
        ),
        migrations.AddField(
            model_name='applicationhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='applicationstagerecord',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_records', to='application.application', verbose_name='申请'),
        ),
        migrations.AddField(
            model_name='applicationstagerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='applicationstagerecord',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_records', to='process.processstagelink', verbose_name='流程-阶段关联'),
        ),
        migrations.AddField(
            model_name='applicationstagerecord',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='process.recruitmentstage', verbose_name='阶段'),
        ),
        migrations.AddField(
            model_name='applicationstagerecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', 'position'], name='application_candida_4361f3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['state', 'current_stage'], name='application_state_c95503_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['stage_deadline'], name='application_stage_d_43264d_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationhistory',
            index=models.Index(fields=['application', 'created_at'], name='application_applica_3f17cd_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationhistory',
            index=models.Index(fields=['action', 'created_at'], name='application_action_3798e6_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstagerecord',
            index=models.Index(fields=['application', 'state'], name='application_applica_7c73cf_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstagerecord',
            index=models.Index(fields=['stage', 'state'], name='application_stage_i_57609f_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstagerecord',
            index=models.Index(fields=['deadline'], name='application_deadlin_53c5b6_idx'),
        ),
    ]
