# Generated by Django 6.0.6 on 2026-08-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_add_user_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationhistory',
            name='action',
            field=models.CharField(choices=[('CREATED', '创建'), ('ADVANCED', '推进'), ('REJECTED', '回退'), ('SKIPPED', '跳过'), ('PAUSED', '暂停'), ('RESUMED', '恢复'), ('OFFER_SENT', '发送Offer'), ('GRABBED', '抢单'), ('TIMEOUT', '超时'), ('UPGRADE_VERSION', '升版本'), ('CHANGE_PROCESS', '更换流程线'), ('AUTO', '自动操作')], max_length=32, verbose_name='操作类型'),
        ),
    ]
