# Generated by Django 6.0.6 on 2026-10-08 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_application_recruit_type'),
        ('candidate', '0012_candidate_archived_at_candidate_is_archived_and_more'),
        ('position', '0004_position_priority'),
        ('process', '0015_processstagelink_stage_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['state', 'is_grabbed', 'deleted_at', 'stage_entered_at'], name='idx_application_state_grab'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['state', 'deleted_at', 'last_advanced_at'], name='idx_application_state_adv'),
        ),
    ]
