# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.entry_condition.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryConditionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.entry_condition.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('process_id', models.CharField(db_index=True, max_length=32, verbose_name='流程ID')),
                ('workflow_version', models.CharField(max_length=20, verbose_name='流程版本')),
                ('rule_name', models.CharField(help_text='限 30 字', max_length=30, verbose_name='规则名称')),
                ('rule_seq', models.IntegerField(db_index=True, default=1, help_text='基于启用规则动态计算', verbose_name='规则序号')),
                ('status', models.CharField(choices=[('ENABLED', '启用'), ('DISABLED', '停用')], db_index=True, default='ENABLED', max_length=16, verbose_name='状态')),
                ('expression', models.CharField(default='1', help_text='使用条件序号和逻辑运算符组合，如 (1 AND 2) OR 3', max_length=500, verbose_name='条件表达式')),
                ('reject_message', models.CharField(blank=True, max_length=200, verbose_name='未满足条件时提示内容')),
                ('match_type', models.CharField(default='ALL', max_length=16, verbose_name='匹配方式')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_condition_rules', to='process.processstagelink', verbose_name='流程-阶段关联')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '进入条件规则',
                'verbose_name_plural': '进入条件规则',
                'db_table': 'entry_condition_rules',
                'ordering': ['link', 'rule_seq'],
            },
        ),
        migrations.CreateModel(
            name='EntryConditionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.entry_condition.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(db_index=True, max_length=32, verbose_name='候选人ID')),
                ('stage_id', models.CharField(max_length=32, verbose_name='阶段ID')),
                ('link_id', models.CharField(db_index=True, max_length=32, verbose_name='流程-阶段关联ID')),
                ('passed', models.BooleanField(db_index=True, verbose_name='是否通过')),
                ('reject_message', models.CharField(blank=True, max_length=500, verbose_name='未满足提示')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='评估快照')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='entry_condition.entryconditionrule', verbose_name='规则')),
            ],
            options={
                'verbose_name': '进入条件评估日志',
                'verbose_name_plural': '进入条件评估日志',
                'db_table': 'entry_condition_logs',
            },
        ),
        migrations.CreateModel(
            name='ConditionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.entry_condition.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('item_seq', models.IntegerField(default=1, help_text='规则内从 1 开始', verbose_name='条件序号')),
                ('condition_type', models.CharField(choices=[('STAGE_STATUS', '阶段条件'), ('CANDIDATE', '候选人'), ('DEMAND', '需求中')], max_length=32, verbose_name='条件类型')),
                ('field', models.CharField(max_length=64, verbose_name='字段名')),
                ('stage_name', models.CharField(blank=True, max_length=64, verbose_name='关联阶段名')),
                ('stage_statuses', models.JSONField(blank=True, default=list, verbose_name='阶段状态多选')),
                ('operator', models.CharField(choices=[('EQ', '='), ('NEQ', '≠'), ('GT', '>'), ('GTE', '≥'), ('LT', '<'), ('LTE', '≤'), ('BETWEEN', '介于'), ('IN', '包含'), ('NOT_IN', '不包含'), ('IS_EMPTY', '为空'), ('IS_NOT_EMPTY', '不为空')], max_length=16, verbose_name='运算符')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='值')),
                ('auto_filter_inactive_users', models.BooleanField(default=False, verbose_name='自动过滤离职人员')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='entry_condition.entryconditionrule', verbose_name='所属规则')),
            ],
            options={
                'verbose_name': '条件项',
                'verbose_name_plural': '条件项',
                'db_table': 'condition_items',
                'ordering': ['rule', 'item_seq'],
            },
        ),
        migrations.AddIndex(
            model_name='entryconditionrule',
            index=models.Index(fields=['link', 'status'], name='entry_condi_link_id_378f66_idx'),
        ),
        migrations.AddIndex(
            model_name='entryconditionrule',
            index=models.Index(fields=['link', 'rule_seq'], name='entry_condi_link_id_9cbc03_idx'),
        ),
        migrations.AddIndex(
            model_name='entryconditionlog',
            index=models.Index(fields=['rule', 'created_at'], name='entry_condi_rule_id_dcd75b_idx'),
        ),
        migrations.AddIndex(
            model_name='entryconditionlog',
            index=models.Index(fields=['candidate_id', 'link_id'], name='entry_condi_candida_cbeb43_idx'),
        ),
    ]
