# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.candidate.models
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.candidate.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, null=True, verbose_name='邮箱')),
                ('gender', models.CharField(blank=True, max_length=8, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('id_card_no', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='身份证号')),
                ('highest_education', models.CharField(blank=True, max_length=50, verbose_name='最高学历')),
                ('work_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='工作年限')),
                ('current_city', models.CharField(blank=True, max_length=50, verbose_name='当前城市')),
                ('expected_city', models.CharField(blank=True, max_length=50, verbose_name='期望城市')),
                ('current_company', models.CharField(blank=True, max_length=100, verbose_name='当前公司')),
                ('current_position', models.CharField(blank=True, max_length=100, verbose_name='当前职位')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='期望薪资')),
                ('resume_file_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='简历文件URL')),
                ('resume_text', models.TextField(blank=True, verbose_name='简历文本')),
                ('referral_type', models.CharField(blank=True, db_index=True, help_text='N+1/N+2/INTERNAL/SOCIAL', max_length=16, verbose_name='推荐类型')),
                ('resume_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='简历评分')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('current_state', django_fsm.FSMField(db_index=True, default='APPLIED', max_length=50, protected=True, verbose_name='当前状态')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False, verbose_name='是否黑名单')),
                ('blacklist_reason', models.CharField(blank=True, max_length=200, verbose_name='黑名单原因')),
                ('moka_candidate_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='摩卡候选人ID')),
            ],
            options={
                'verbose_name': '候选人',
                'verbose_name_plural': '候选人',
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='CandidateHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.candidate.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64, verbose_name='操作')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
            ],
            options={
                'verbose_name': '候选人历史',
                'verbose_name_plural': '候选人历史',
                'db_table': 'candidate_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateTag',
            fields=[
                ('id', models.CharField(default=apps.candidate.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='颜色')),
                ('category', models.CharField(blank=True, max_length=32, verbose_name='分类')),
            ],
            options={
                'verbose_name': '候选人标签',
                'verbose_name_plural': '候选人标签',
                'db_table': 'candidate_tags',
            },
        ),
    ]
