# Generated by Django 5.0.6 on 2026-06-30 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ('-created_at',), 'verbose_name': '推荐记录', 'verbose_name_plural': '推荐记录'},
        ),
    ]
