# Generated by Django 6.0.6 on 2026-08-31 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='规则名称')),
                ('category', models.CharField(choices=[('TCA', '触发-条件-动作'), ('CONSTRAINT', '约束校验'), ('POLICY', '访问控制')], default='TCA', max_length=16, verbose_name='规则族')),
                ('source_app', models.CharField(blank=True, default='', help_text='automation/entry_condition/time_limit/campus_control/mou/field_acl/process', max_length=64, verbose_name='来源 app')),
                ('trigger_type', models.CharField(choices=[('STAGE_ENTERED', '进入阶段'), ('STATE_CHANGED', '状态变更'), ('EVALUATION_SUBMITTED', '评价提交'), ('SCHEDULED', '定时巡检'), ('STAGE_DWELL_TIMEOUT', '阶段停留超时'), ('OFFER_SUBMITTED', '提交 Offer'), ('BUSINESS_EVENT', '业务事件')], max_length=32, verbose_name='触发类型')),
                ('trigger_timing', models.CharField(blank=True, max_length=32, null=True, verbose_name='执行时机')),
                ('trigger_delay_hours', models.IntegerField(blank=True, null=True, verbose_name='延迟小时')),
                ('trigger_delay_working_days', models.IntegerField(blank=True, null=True, verbose_name='延迟工作日')),
                ('scope_json', models.JSONField(default=dict, help_text='标准 scope 结构见 §2.6', verbose_name='适用范围')),
                ('priority', models.CharField(choices=[('P0', 'P0-最高'), ('P1', 'P1-中'), ('P2', 'P2-低')], default='P1', max_length=4, verbose_name='优先级')),
                ('priority_rank', models.IntegerField(default=0, verbose_name='优先级细排')),
                ('status', models.CharField(choices=[('ENABLED', '启用'), ('DISABLED', '停用')], default='ENABLED', max_length=16, verbose_name='状态')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用开关')),
                ('failure_rate_threshold', models.FloatField(default=0.5, verbose_name='熔断失败率阈值')),
                ('condition_expression', models.CharField(blank=True, default='', help_text='(1 AND 2) OR 3，引用 Condition.seq', max_length=500, verbose_name='条件表达式')),
                ('condition_logic', models.CharField(choices=[('ALL', '全部满足'), ('ANY', '任一满足')], default='ALL', max_length=8, verbose_name='条件逻辑（兜底）')),
                ('config_json', models.JSONField(default=dict, verbose_name='家族专属逃逸字段')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '统一规则',
                'verbose_name_plural': '统一规则',
                'db_table': 'rule_engine_rules',
                'ordering': ['priority', 'priority_rank'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('seq', models.IntegerField(verbose_name='执行顺序')),
                ('action_type', models.CharField(choices=[('AUTO_ADVANCE', '自动推进'), ('SKIP_TO', '跳到指定阶段'), ('REMIND', '发提醒'), ('REJECT_TO_POOL', '入公共人才库'), ('ALLOW', '放行'), ('REJECT', '拦截'), ('LOCK', '锁定阶段'), ('UNLOCK', '解锁'), ('BLOCK_HARD', '硬约束拦截'), ('BLOCK_SOFT', '软约束提示'), ('ASSIGN_HANDLER', '指派处理人'), ('SET_PERMISSION', '设置字段权限')], max_length=32, verbose_name='动作类型')),
                ('params_json', models.JSONField(default=dict, verbose_name='动作参数')),
                ('enabled', models.BooleanField(default=True, verbose_name='动作开关')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rule_engine.rule', verbose_name='所属规则')),
            ],
            options={
                'verbose_name': '统一动作项',
                'verbose_name_plural': '统一动作项',
                'db_table': 'rule_engine_actions',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecutionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('rule_category', models.CharField(choices=[('TCA', '触发-条件-动作'), ('CONSTRAINT', '约束校验'), ('POLICY', '访问控制')], max_length=16, verbose_name='规则族（冗余）')),
                ('trigger_type', models.CharField(max_length=32, verbose_name='触发类型')),
                ('candidate_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='候选人')),
                ('application_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='应聘')),
                ('stage_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='阶段')),
                ('link_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='阶段链接')),
                ('process_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='流程')),
                ('evaluate_result', models.CharField(choices=[('MATCHED', '命中'), ('UNMATCHED', '未命中'), ('ERROR', '错误'), ('ALLOWED', '放行'), ('REJECTED', '拦截'), ('BLOCKED', '阻塞'), ('SKIPPED', '跳过'), ('LOCKED', '已锁定')], max_length=16, verbose_name='执行结果')),
                ('action_taken', models.CharField(blank=True, default='', max_length=200, verbose_name='实际动作摘要')),
                ('action_type', models.CharField(blank=True, default='', max_length=64, verbose_name='执行动作类型')),
                ('skip_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='跳过原因')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='异常信息')),
                ('execution_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('actor_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='触发人')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='触发时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='rule_engine.rule', verbose_name='来源规则')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '统一执行日志',
                'verbose_name_plural': '统一执行日志',
                'db_table': 'rule_engine_execution_logs',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('seq', models.IntegerField(help_text='从 1 起，供 condition_expression 引用', verbose_name='规则内序号')),
                ('condition_type', models.CharField(choices=[('STAGE_STATUS', '阶段状态'), ('CANDIDATE', '候选人'), ('DEMAND', '需求'), ('CUSTOM', '自定义')], default='CUSTOM', max_length=16, verbose_name='条件类型')),
                ('field', models.CharField(max_length=64, verbose_name='字段名')),
                ('operator', models.CharField(choices=[('EQ', '等于'), ('NEQ', '不等于'), ('GT', '大于'), ('GTE', '大于等于'), ('LT', '小于'), ('LTE', '小于等于'), ('BETWEEN', '区间'), ('IN', '属于集合'), ('NOT_IN', '不属于集合'), ('IS_EMPTY', '为空'), ('IS_NOT_EMPTY', '不为空')], max_length=16, verbose_name='运算符')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='比较值')),
                ('stage_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='阶段名')),
                ('stage_statuses', models.JSONField(blank=True, null=True, verbose_name='阶段状态集合')),
                ('auto_filter_inactive_users', models.BooleanField(default=False, verbose_name='自动过滤停用人员')),
                ('meta_json', models.JSONField(default=dict, verbose_name='扩展（BETWEEN 的 min/max 等）')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rule_engine.rule', verbose_name='所属规则')),
            ],
            options={
                'verbose_name': '统一条件项',
                'verbose_name_plural': '统一条件项',
                'db_table': 'rule_engine_conditions',
                'ordering': ['seq'],
                'unique_together': {('rule', 'seq')},
            },
        ),
    ]
