# Generated by Django 6.0.6 on 2026-08-31 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='legacy_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='legacy 表主键，如 automation.AutomationRule.id', max_length=64, verbose_name='来源记录 ID'),
        ),
        migrations.AddField(
            model_name='rule',
            name='legacy_model',
            field=models.CharField(blank=True, default='', help_text='legacy app.Model 路径，如 automation.AutomationRule', max_length=128, verbose_name='来源模型'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['source_app', 'legacy_id'], name='rule_src_legacy'),
        ),
    ]
