# Generated by Django 6.0.6 on 2026-09-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0002_rule_legacy_id_rule_legacy_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='operator',
            field=models.CharField(choices=[('EQ', '等于'), ('NEQ', '不等于'), ('GT', '大于'), ('GTE', '大于等于'), ('LT', '小于'), ('LTE', '小于等于'), ('BETWEEN', '区间'), ('IN', '属于集合'), ('NOT_IN', '不属于集合'), ('IS_EMPTY', '为空'), ('IS_NOT_EMPTY', '不为空'), ('CONTAINS', '包含'), ('NOT_CONTAINS', '不包含'), ('REGEX_MATCH', '正则匹配')], max_length=16, verbose_name='运算符'),
        ),
    ]
