# Generated by Django 6.0.6 on 2026-10-08 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0003_alter_condition_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['trigger_type', 'enabled', 'status', 'deleted_at'], name='idx_rule_trigger_enabled'),
        ),
        migrations.AddIndex(
            model_name='ruleexecutionlog',
            index=models.Index(fields=['rule', 'evaluate_result'], name='idx_rulelog_rule_eval'),
        ),
    ]
