# Generated by Django 6.0.6 on 2026-09-12 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=128, verbose_name='表单名称')),
                ('form_type', models.CharField(choices=[('application', '申请表'), ('registration', '登记表')], default='registration', max_length=32, verbose_name='表单类型')),
                ('departments', models.JSONField(blank=True, default=list, verbose_name='适用部门')),
                ('mode', models.CharField(default='default', max_length=32, verbose_name='填写模式')),
                ('fields', models.JSONField(blank=True, default=list, verbose_name='字段配置')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '登记/申请表',
                'verbose_name_plural': '登记/申请表',
                'db_table': 'sr_registration_forms',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
