# Generated by Django 6.0.6 on 2026-08-20 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='人员编码')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('bu', models.CharField(choices=[('能电BG', '能电BG'), ('三到BG', '三到BG'), ('综合BG', '综合BG'), ('醒电BG', '醒电BG')], max_length=16, verbose_name='部门')),
                ('school', models.CharField(choices=[('985', '985'), ('211', '211'), ('双一流', '双一流'), ('其他', '其他')], max_length=16, verbose_name='院校标签')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=4, verbose_name='性别')),
                ('major', models.CharField(choices=[('工学', '工学'), ('其他', '其他')], max_length=16, verbose_name='专业标签')),
                ('month', models.CharField(max_length=8, verbose_name='招聘月份')),
                ('status', models.CharField(choices=[('已入职', '已入职'), ('已Offer', '已Offer'), ('候选池', '候选池')], default='已入职', max_length=16, verbose_name='状态')),
                ('counted', models.BooleanField(default=True, verbose_name='计入核算')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '人员主数据',
                'verbose_name_plural': '人员主数据',
                'ordering': ['bu', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ControlRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('dim', models.CharField(choices=[('院校标签', '院校标签'), ('专业标签', '专业标签'), ('性别', '性别')], max_length=16, verbose_name='维度')),
                ('group', models.CharField(max_length=32, verbose_name='分组')),
                ('target', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='目标占比')),
                ('lo', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='下限占比')),
                ('hi', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='上限占比')),
                ('strength', models.CharField(choices=[('硬约束', '硬约束'), ('软约束', '软约束'), ('仅提示', '仅提示')], default='硬约束', max_length=16, verbose_name='控制强度')),
                ('whole', models.IntegerField(default=0, verbose_name='整体目标人数')),
                ('month_target', models.IntegerField(default=0, verbose_name='本月目标人数')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '管控规则',
                'verbose_name_plural': '管控规则',
                'ordering': ['dim', 'group'],
                'unique_together': {('dim', 'group')},
            },
        ),
    ]
