# Generated by Django 6.0.6 on 2026-08-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controldimension',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='维度'),
        ),
    ]
