# Generated by Django 6.0.6 on 2026-08-21 05:51
# 手动调整操作顺序：year 字段必须先于 AlterUniqueTogether 添加，
# 否则在 MySQL/SQLite 上会因唯一约束引用尚不存在的列而失败。

from django.db import migrations, models

import apps.campus_control.models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_control', '0002_alter_controldimension_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlrule',
            options={'ordering': ['bu', 'position', 'level', 'dimension', 'indicator', 'year'], 'verbose_name': '管控规则', 'verbose_name_plural': '管控规则'},
        ),
        # 先新增字段（含 year），再改唯一约束 / 删旧字段
        migrations.AddField(
            model_name='controlrule',
            name='annual_target',
            field=models.IntegerField(default=0, verbose_name='年度目标人数'),
        ),
        migrations.AddField(
            model_name='controlrule',
            name='monthly_targets',
            field=models.JSONField(default=apps.campus_control.models._default_monthly, verbose_name='12个月目标'),
        ),
        migrations.AddField(
            model_name='controlrule',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='规划年度'),
        ),
        migrations.AlterUniqueTogether(
            name='controlrule',
            unique_together={('bu', 'position', 'level', 'dimension', 'indicator', 'year')},
        ),
        migrations.DeleteModel(
            name='ControlHeadcount',
        ),
        migrations.RemoveField(
            model_name='controlrule',
            name='hi',
        ),
        migrations.RemoveField(
            model_name='controlrule',
            name='lo',
        ),
    ]
