# Generated by Django 6.0.6 on 2026-08-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_control', '0003_alter_controlrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='actual_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际入职日期'),
        ),
        migrations.AddField(
            model_name='person',
            name='expected_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计入职日期'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('在职', '在职'), ('在途Offer', '在途Offer'), ('在途待入职', '在途待入职'), ('候选池', '候选池')], default='在职', max_length=16, verbose_name='状态'),
        ),
    ]
