# Generated by Django 6.0.6 on 2026-08-26 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_control', '0004_person_actual_entry_date_person_expected_entry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDimensionValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=64, verbose_name='取值')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_values', to='campus_control.controldimension', verbose_name='维度')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_values', to='campus_control.person', verbose_name='人员')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '人员维度取值',
                'verbose_name_plural': '人员维度取值',
                'ordering': ['person', 'dimension'],
                'unique_together': {('person', 'dimension')},
            },
        ),
    ]
