# Generated by Django 6.0.6 on 2026-09-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_control', '0008_controlrule_rollover_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='关联用户ID'),
        ),
    ]
