# Generated by Django 6.0.6 on 2026-10-08 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_control', '0009_person_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status', 'bu', 'school'], name='idx_person_status_bu_school'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status', 'position', 'level'], name='idx_person_status_pos_level'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status', 'major', 'sex'], name='idx_person_status_major_sex'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status', 'bu', 'position'], name='idx_person_status_bu_pos'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status', 'school', 'major'], name='idx_person_status_school_major'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status', 'actual_entry_date'], name='idx_person_status_entry'),
        ),
    ]
