# Generated by Django 5.0.6 on 2026-06-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_exporttask_requested_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_data_subscription',
            },
        ),
    ]
