# Generated by Django 6.0.6 on 2026-08-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_datasubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasubscription',
            options={'ordering': ['-created_at'], 'verbose_name': '数据订阅', 'verbose_name_plural': '数据订阅'},
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='channel',
            field=models.CharField(blank=True, default='SYSTEM', max_length=16, verbose_name='渠道'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='filters',
            field=models.TextField(blank=True, default='', verbose_name='过滤条件'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次运行'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='metric',
            field=models.CharField(blank=True, default='all', max_length=32, verbose_name='指标'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次运行'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='recipients',
            field=models.TextField(blank=True, default='', verbose_name='收件人'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='resource',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='资源'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='run_count',
            field=models.IntegerField(default=0, verbose_name='运行次数'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='schedule',
            field=models.CharField(blank=True, default='DAILY', max_length=16, verbose_name='周期'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='schedule_time',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='发送时间'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='订阅人ID'),
        ),
        migrations.AddField(
            model_name='datasubscription',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='订阅人'),
        ),
        migrations.AlterField(
            model_name='datasubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='datasubscription',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasubscription',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='名称'),
        ),
    ]
