# Generated by Django 6.0.6 on 2026-08-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_integrationconfig_encrypted_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='config',
            field=models.JSONField(default=dict, help_text='API URL, 签名名, 模板号 等', verbose_name='非敏感配置'),
        ),
    ]
