# Generated by Django 6.0.6 on 2026-08-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_alter_integrationconfig_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfig',
            name='provider',
            field=models.CharField(blank=True, db_index=True, default='', help_text='背调场景下区分多家供应商，如 quanjing/xinda/andun', max_length=64, verbose_name='供应商代码'),
        ),
        migrations.AddField(
            model_name='integrationsynclog',
            name='direction',
            field=models.CharField(blank=True, default='', help_text='OUT 出向 / IN 入向', max_length=8, verbose_name='方向'),
        ),
        migrations.AddField(
            model_name='integrationsynclog',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)'),
        ),
        migrations.AddField(
            model_name='integrationsynclog',
            name='endpoint',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='接口路径'),
        ),
        migrations.AddField(
            model_name='integrationsynclog',
            name='method',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='type',
            field=models.CharField(choices=[('MOKA', '摩卡 HRIS'), ('EMAIL', '邮件服务'), ('WECOM', '企业微信'), ('SMS', '短信服务'), ('BACKGROUND_CHECK', '背调服务'), ('PORTAL', '招聘门户')], max_length=32, verbose_name='类型'),
        ),
    ]
