# Generated by Django 6.0.6 on 2026-08-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_integrationconfig_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsynclog',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text='供应商订单号/回执号(number)，便于幂等与展示', max_length=128, verbose_name='外部单号'),
        ),
        migrations.AddField(
            model_name='integrationsynclog',
            name='request_data',
            field=models.JSONField(blank=True, help_text='回调等入向请求的原始负载，便于审计与排障', null=True, verbose_name='原始请求体'),
        ),
        migrations.AddIndex(
            model_name='integrationsynclog',
            index=models.Index(fields=['config', 'sync_type', 'external_ref', 'status'], name='idx_synclog_cb_idem'),
        ),
    ]
