# Generated by Django 6.0.6 on 2026-08-28 03:28

import django.db.models.deletion
from django.db import migrations, models

import apps.integration.models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_integrationsynclog_external_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheckOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.integration.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('order_number', models.CharField(help_text='平台生成，全链路主键', max_length=64, verbose_name='订单号(number)')),
                ('candidate_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='候选人ID')),
                ('candidate_name', models.CharField(blank=True, default='', max_length=64, verbose_name='候选人姓名')),
                ('status', models.IntegerField(choices=[(0, '已受理/已下单'), (1, '已完成'), (2, '待授权'), (3, '背调中'), (4, '授权过期'), (5, '待支付'), (6, '已取消'), (7, '阶段报告'), (8, '授权撤销')], db_index=True, default=0, verbose_name='订单状态')),
                ('status_name', models.CharField(blank=True, default='', max_length=32, verbose_name='状态名称')),
                ('risk_level', models.IntegerField(blank=True, help_text='1低/2中/3高/4无/9未评级', null=True, verbose_name='风险等级')),
                ('report_url', models.CharField(blank=True, default='', max_length=512, verbose_name='报告地址')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('latest_payload', models.JSONField(blank=True, null=True, verbose_name='最近一次回调/响应原始体')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_orders', to='integration.integrationconfig', verbose_name='供应商配置')),
            ],
            options={
                'verbose_name': '背调订单',
                'verbose_name_plural': '背调订单',
                'db_table': 'background_check_orders',
                'ordering': ['-created_at'],
                'unique_together': {('config', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='BackgroundCheckOrderEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.integration.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('from_status', models.IntegerField(blank=True, null=True, verbose_name='原状态')),
                ('to_status', models.IntegerField(verbose_name='新状态')),
                ('risk_level', models.IntegerField(blank=True, null=True, verbose_name='风险等级')),
                ('report_url', models.CharField(blank=True, default='', max_length=512, verbose_name='报告地址')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('source', models.CharField(help_text='CREATE/CALLBACK/CANCEL', max_length=16, verbose_name='来源')),
                ('is_legal_transition', models.BooleanField(default=True, verbose_name='是否合法转移')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='原始负载')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_order_events', to='integration.integrationconfig', verbose_name='供应商配置')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integration.backgroundcheckorder', verbose_name='订单')),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bg_order_events', to='integration.integrationsynclog', verbose_name='关联同步日志')),
            ],
            options={
                'verbose_name': '背调订单事件',
                'verbose_name_plural': '背调订单事件',
                'db_table': 'background_check_order_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
