# Generated by Django 6.0.6 on 2026-09-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_backgroundcheckorder_backgroundcheckorderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundcheckorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='backgroundcheckorderevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='integrationsynclog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
    ]
