# Generated by Django 6.0.6 on 2026-09-14 17:31

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.accounts.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱')),
                ('code_hash', models.CharField(max_length=128, verbose_name='验证码 SHA-256')),
                ('purpose', models.CharField(default='REGISTER', max_length=32, verbose_name='用途')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('attempts', models.IntegerField(default=0, verbose_name='错误尝试次数')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('USED', '已使用'), ('EXPIRED', '已过期'), ('LOCKED', '已锁定')], default='ACTIVE', max_length=16, verbose_name='状态')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'db_table': 'email_verification_codes',
                'indexes': [models.Index(fields=['email', 'purpose', 'status'], name='email_verif_email_4a2131_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_42d424_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.accounts.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('full_name', models.CharField(blank=True, max_length=64, verbose_name='姓名')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('EXPIRED', '已过期')], db_index=True, default='PENDING', max_length=16, verbose_name='状态')),
                ('email_verified', models.BooleanField(default=False, verbose_name='邮箱已验证')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '注册申请',
                'verbose_name_plural': '注册申请',
                'db_table': 'registration_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
