import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import UnoCSS from 'unocss/vite'
// Plan O Task 8: 产物分析
import { visualizer } from 'rollup-plugin-visualizer'
import path from 'path'
import fs from 'fs'
import { execSync } from 'child_process'
import { fileURLToPath } from 'url'
// @ts-expect-error: config file is outside tsconfig.node.json file list used for Vite config
import config from './src/config'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// 2026-08-17 寇豆码: 富文本编辑器 (wangEditor 5) 及其全部间接依赖。
// wangEditor 体积 ~860KB, 只有「政策制度/文档说明」编辑页用到; 若落进默认的
// vendor-misc, 会被 index.html modulepreload 拖到首屏 (55KB -> 860KB)。
// 这里按 node_modules 目录段精确匹配, 单独切一个 chunk, 随路由懒加载。
// 注意: 必须用 `/node_modules/<pkg>/` 全段匹配, 不能用 includes('slate') —
//       会误伤 translate 之类的包名。
const RICH_EDITOR_PKGS = [
  '@wangeditor',
  '@uppy',
  'slate',
  'slate-history',
  'snabbdom',
  'dom7',
  'is-hotkey',
  'is-url',
  'nanoid',
  'event-emitter',
  'es5-ext',
  'es6-symbol',
  'next-tick',
  'd',
  'html-void-elements',
  'i18next',
  'scroll-into-view-if-needed',
  'compute-scroll-into-view',
  'prismjs',
  'namespace-emitter',
  'mime-match',
  'wildcard',
  'lodash.camelcase',
  'lodash.clonedeep',
  'lodash.debounce',
  'lodash.foreach',
  'lodash.isequal',
  'lodash.throttle',
  'lodash.toarray',
]

/** 判断模块 id 是否属于指定 node_modules 包 (按路径段匹配, 避免子串误伤) */
function isNodeModulePkg(id: string, pkg: string): boolean {
  return id.includes(`/node_modules/${pkg}/`)
}

// === 系统升级版本标识（2026-09-23 新增）===
// 目的：前端轮询线上 version.json，与构建期注入的 __APP_VERSION__ 比对；不一致（部署了新构建）
//       → 弹「系统已升级」确认框，由用户决定是否刷新页面（避免旧 bundle 静默运行）。
// 实现：config 钩子在一次加载期（dev/prod 一致）生成 public/version.json 并注入 __APP_VERSION__。
//   - public/version.json 作为「线上当前版本」源（Vite 将 public/ 拷到构建产物根目录，跨 base 稳定）。
//   - __APP_VERSION__ 是编译期常量，旧 bundle 里仍是上次构建的值 → 线上更新后比对即不一致。
function resolveAppVersion(): string {
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
  } catch {
    // 无 git 环境（如 CI 某些场景）→ 退化为构建时间戳，保证每次构建值不同也能触发检测
    return new Date().toISOString()
  }
}

function appVersionPlugin() {
  const version = resolveAppVersion()
  const buildTime = new Date().toISOString()
  const writeVersionJson = () => {
    try {
      fs.mkdirSync(path.resolve(__dirname, 'public'), { recursive: true })
      fs.writeFileSync(
        path.resolve(__dirname, 'public', 'version.json'),
        JSON.stringify({ version, buildTime }, null, 2),
      )
    } catch (e) {
      console.warn('[app-version] version.json 写入失败（不影响构建）', e)
    }
  }
  // 生成源码模块导出版本常量：相比 define 全局替换，此方式在 dev/prod 行为完全一致，
  // 且旧 bundle 天然保留旧版本值（编译期写入），部署新版本后线上 version.json 变化即触发比对。
  const writeVersionModule = () => {
    try {
      const dir = path.resolve(__dirname, 'src', 'generated')
      fs.mkdirSync(dir, { recursive: true })
      fs.writeFileSync(
        path.resolve(dir, 'appVersion.ts'),
        [
          '// AUTO-GENERATED by vite app-version plugin. DO NOT EDIT.',
          `export const APP_VERSION = ${JSON.stringify(version)}`,
          `export const APP_BUILD_TIME = ${JSON.stringify(buildTime)}`,
          '',
        ].join('\n'),
      )
    } catch (e) {
      console.warn('[app-version] 版本模块写入失败（不影响构建）', e)
    }
  }
  return {
    name: 'app-version',
    config() {
      // dev/prod 均执行：确保 server 一起步就生成 version.json 与版本模块。
      writeVersionJson()
      writeVersionModule()
    },
  }
}

export default defineConfig(({ mode }) => ({
  // 2026-06-29 花无缺: 生产环境 base='/static/' 让 chunk 走 /static/assets/xxx,
  //   跟 Django STATIC_URL='/static/' + whitenoise 对齐.
  // ⚠️ dev 模式必须用 '/', 否则 index.html 里所有 asset 路径都带 /static/ 前缀,
  //   Vite dev server 仍能 serve (它有 fallback), 但 SPA history 路由深链
  //   (如 /settings/mou 直访) 会让浏览器请求 /static/settings/mou, 触发 whitenoise 提示.
  base: mode === 'development' ? '/' : '/static/',
  plugins: [
    appVersionPlugin(),
    vue(),
    UnoCSS(),
    // Plan O Task 8: 产物分析 (默认不启用, 仅 ANALYZE=1 时)
    mode === 'production' && process.env.ANALYZE === '1'
      ? visualizer({
          filename: 'dist/stats.html',
          gzipSize: true,
          brotliSize: true,
          template: 'treemap',
        })
      : null,
  ].filter(Boolean),
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: config.frontend.port,
    proxy: {
      [config.api.baseUrl]: {
        target: config.backend.url,
        changeOrigin: true,
      },
      // 附件等用户上传的 media 文件走 Django serve, 经 Vite 代理转发, 避免前端跨端口直连 8000。
      '/media': {
        target: config.backend.url,
        changeOrigin: true,
      },
    },
  },
  // 依赖预构建 — dev 启动 + build 前都会跑
  // naive-ui 2.x 是分模块 ESM,内部 cssr 库 (treemate/async-validator/seemly/...) 在
  // top-level 就有副作用(createApp 时立刻执行 setup),必须让 esbuild 预构建把它们
  // 锁成单一 .js 产物。否则 rollup 后续拆分 chunk 会重排求值顺序,触发 TDZ 白屏。
  // 2026-06-15: 增加 'naive-ui' 到 include,让 dev/prod 行为一致
  optimizeDeps: {
    include: ['naive-ui'],
  },
  build: {
    outDir: 'dist',
    sourcemap: false,
    // Plan O: 优化产物
    // 2026-06-29: target 升 es2022 — main.ts 用了 top-level await (await fetchMe() 在 mount 前),
    //            es2020 不支持 top-level await, build:nocheck 也会 esbuild 报错
    target: 'es2022',
    cssCodeSplit: true,
    chunkSizeWarningLimit: 1500,
    // 手动分块: 第三方库单独, 路由懒加载 chunk 由 router 控制
    rollupOptions: {
      output: {
        manualChunks: (id) => {
          if (id.includes('node_modules')) {
            // 富文本编辑器: 放最前面, 优先于 lodash -> vendor-naive-ui 的规则,
            // 保证 lodash.xxx 这些只被 wangEditor 用到的微包不落首屏 chunk
            if (RICH_EDITOR_PKGS.some((pkg) => isNodeModulePkg(id, pkg))) {
              return 'vendor-rich-editor'
            }
            // Naive UI 生态 + 它全部间接依赖必须放同一 chunk
            // (treemate / async-validator / seemly / vueuc / vdirs / vooks / csstype /
            //  highlight.js / lodash(-es) / date-fns / date-fns-tz / @css-render 系
            //  — naive-ui 2.44.1 间接依赖约 10+ 个小库,被拆到 vendor-misc 后
            //  rollup 重排求值顺序,出现 TDZ 'Cannot access ma before initialization',
            //  Vue mount 失败 #app 空)
            // 2026-06-15: 把 naive-ui 全部间接依赖归到 vendor-naive-ui, 消除 vendor-misc
            if (
              id.includes('naive-ui') ||
              id.includes('@css-render') ||
              id.includes('css-render') ||
              id.includes('seemly') ||
              id.includes('evtd') ||
              id.includes('date-fns') ||
              id.includes('treemate') ||
              id.includes('vueuc') ||
              id.includes('vdirs') ||
              id.includes('vooks') ||
              id.includes('async-validator') ||
              id.includes('csstype') ||
              id.includes('highlight.js') ||
              id.includes('lodash')
            ) {
              return 'vendor-naive-ui'
            }
            // Vue 核心
            if (id.includes('@vue') || id.includes('vue-router') || id.includes('pinia') || id.includes('@vueuse')) {
              return 'vendor-vue'
            }
            // Icons
            if (id.includes('@vicons') || id.includes('@iconify')) {
              return 'vendor-icons'
            }
            // UnoCSS
            if (id.includes('unocss') || id.includes('@unocss')) {
              return 'vendor-unocss'
            }
            // 其他 vendor (理论上不该再有,留 fallback)
            return 'vendor-misc'
          }
          // src 内的工具库
          if (id.includes('/src/utils/') || id.includes('/src/api/')) {
            return 'app-utils'
          }
        },
        // 启用 chunk 文件名模板 (含 hash)
        chunkFileNames: 'assets/[name]-[hash].js',
        entryFileNames: 'assets/[name]-[hash].js',
      },
    },
  },
}))
