# Generated by Django 6.0.6 on 2026-08-18 11:24

import django.db.models.deletion
from django.db import migrations, models


def _backfill_dict_number(apps, schema_editor):
    """为历史空 dict_number 行按 code 顺序补 D{n} 编号。"""
    DictionaryType = apps.get_model('dictionary', 'DictionaryType')
    n = 0
    for t in DictionaryType.objects.filter(dict_number='').order_by('code'):
        n += 1
        t.dict_number = f'D{n}'
        t.save(update_fields=['dict_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_init_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='dictionaryitem',
            name='english_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='英文名称'),
        ),
        migrations.AddField(
            model_name='dictionaryitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.dictionaryitem', verbose_name='父级元素'),
        ),
        migrations.AddField(
            model_name='dictionarytype',
            name='dict_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='字典编号'),
        ),
        migrations.AddField(
            model_name='dictionarytype',
            name='english_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='英文名称'),
        ),
        migrations.AddField(
            model_name='dictionarytype',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='dictionarytype',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='是否系统预置'),
        ),
        migrations.RunPython(_backfill_dict_number, migrations.RunPython.noop),
    ]
