# Generated by Django 6.0.6 on 2026-08-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0002_gdpr_verification_code_hash'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gdprrequest',
            new_name='gdpr_reques_verific_e68f9c_idx',
            old_name='idx_gdpr_expires',
        ),
    ]
