# Generated by Django 6.0.6 on 2026-09-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0003_rename_idx_gdpr_expires_gdpr_reques_verific_e68f9c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdprrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
    ]
