# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.onboarding.models
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0002_candidate_extra'),
        ('offer', '0001_initial'),
        ('position', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.onboarding.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='入职日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际入职日期')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='试用期结束日期')),
                ('todo_list', models.JSONField(default=list, verbose_name='入职待办清单')),
                ('todo_completed', models.JSONField(default=dict, verbose_name='待办完成情况')),
                ('state', django_fsm.FSMField(db_index=True, default='PENDING', max_length=50, protected=True, verbose_name='入职状态')),
                ('regularization_result', models.CharField(blank=True, max_length=32, verbose_name='转正结果')),
                ('regularization_at', models.DateTimeField(blank=True, null=True, verbose_name='转正时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboardings', to='candidate.candidate', verbose_name='候选人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding', to='offer.offer', verbose_name='Offer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboardings', to='position.position', verbose_name='职位')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '入职流程',
                'verbose_name_plural': '入职流程',
                'db_table': 'onboardings',
                'indexes': [models.Index(fields=['state', 'start_date'], name='onboardings_state_3088ce_idx')],
            },
        ),
    ]
