# Generated by Django 6.0.6 on 2026-09-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_position_demand_alter_position_process_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='recruit_type',
            field=models.CharField(choices=[('social', 'social'), ('campus', 'campus')], db_index=True, default='social', max_length=16, verbose_name='招聘类型'),
        ),
    ]
