# Generated by Django 6.0.6 on 2026-09-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_position_recruit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='priority',
            field=models.CharField(blank=True, choices=[('高', '高'), ('中', '中'), ('低', '低')], default='中', max_length=10, verbose_name='优先级'),
        ),
    ]
