# Generated by Django 6.0.6 on 2026-08-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_condition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='entryconditionrule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
    ]
