# Generated by Django 6.0.6 on 2026-10-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_condition', '0003_remap_legacy_candidate_field_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionitem',
            name='condition_type',
            field=models.CharField(choices=[('STAGE_STATUS', '阶段条件'), ('CANDIDATE', '候选人'), ('DEMAND', '需求中'), ('POSITION', '职位中')], max_length=32, verbose_name='条件类型'),
        ),
    ]
