# Generated by Django 6.0.6 on 2026-10-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_condition', '0004_alter_conditionitem_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionitem',
            name='condition_type',
            field=models.CharField(choices=[('STAGE_STATUS', '阶段条件'), ('CANDIDATE', '候选人'), ('DEMAND', '需求中'), ('POSITION', '职位中'), ('METRIC', '指标')], max_length=32, verbose_name='条件类型'),
        ),
        migrations.AlterField(
            model_name='conditionitem',
            name='operator',
            field=models.CharField(choices=[('EQ', '='), ('NEQ', '≠'), ('GT', '>'), ('GTE', '≥'), ('LT', '<'), ('LTE', '≤'), ('BETWEEN', '介于'), ('IN', '包含'), ('NOT_IN', '不包含'), ('IS_EMPTY', '为空'), ('IS_NOT_EMPTY', '不为空'), ('CONTAINS', '包含'), ('NOT_CONTAINS', '不包含'), ('REGEX_MATCH', '正则匹配')], max_length=16, verbose_name='运算符'),
        ),
    ]
