# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.interview.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0002_application_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.interview.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='面试编号')),
                ('round_number', models.IntegerField(default=1, verbose_name='轮次')),
                ('format', models.CharField(choices=[('SINGLE', '单面'), ('JOINT', '联合面试'), ('COMPREHENSIVE', '综合面试'), ('VIDEO', '视频面试'), ('PHONE', '电话面试')], default='SINGLE', max_length=16, verbose_name='形式')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='安排时间')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='时长（分钟）')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('meeting_url', models.URLField(blank=True, max_length=500, verbose_name='视频链接')),
                ('status', models.CharField(choices=[('SCHEDULED', '已安排'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消'), ('NO_SHOW', '候选人未到场')], db_index=True, default='SCHEDULED', max_length=16, verbose_name='面试状态')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='application.application', verbose_name='申请')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('interviewers', models.ManyToManyField(related_name='interview_assignments', to=settings.AUTH_USER_MODEL, verbose_name='面试官')),
                ('stage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='application.applicationstagerecord', verbose_name='阶段记录')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '面试',
                'verbose_name_plural': '面试',
                'db_table': 'interviews',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.interview.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('scores', models.JSONField(default=dict, help_text='{"专业能力": 4, "沟通能力": 5}', verbose_name='评分维度')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='综合评分')),
                ('recommendation', models.CharField(help_text='STRONGLY_RECOMMEND/RECOMMEND/NEUTRAL/NOT_RECOMMEND/STRONGLY_NOT_RECOMMEND', max_length=32, verbose_name='推荐结果')),
                ('comment', models.TextField(help_text='限 1000 字', verbose_name='评语')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提交时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interview.interview', verbose_name='面试')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='面试官')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '面试评价',
                'verbose_name_plural': '面试评价',
                'db_table': 'interview_evaluations',
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', 'scheduled_at'], name='interviews_applica_d4b49e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewevaluation',
            unique_together={('interview', 'interviewer')},
        ),
    ]
