# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.talent_pool.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0002_candidate_extra'),
        ('position', '0001_initial'),
        ('process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPoolTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.talent_pool.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('category', models.CharField(db_index=True, help_text='SKILL/INDUSTRY/LEVEL/LOCATION/SOURCE', max_length=32, verbose_name='分类')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='颜色')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '人才库标签',
                'verbose_name_plural': '人才库标签',
                'db_table': 'talent_pool_tags',
            },
        ),
        migrations.CreateModel(
            name='TalentPoolEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.talent_pool.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('REJECTED', '本流程未通过'), ('WITHDRAWN', '候选人主动撤回'), ('TIMEOUT', '超时归档'), ('ACTIVE_REJECT', '主动拒绝入库'), ('MANUAL', '手动入库')], max_length=16, verbose_name='入库来源')),
                ('source_detail', models.CharField(blank=True, max_length=200, verbose_name='来源详情')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('activated_count', models.IntegerField(default=0, verbose_name='激活次数')),
                ('last_activated_at', models.DateTimeField(blank=True, null=True, verbose_name='最后激活时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='在库')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talent_pool_entries', to='candidate.candidate', verbose_name='候选人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('last_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='position.position', verbose_name='最近职位')),
                ('last_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='process.recruitmentstage', verbose_name='最后阶段')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '人才库条目',
                'verbose_name_plural': '人才库条目',
                'db_table': 'talent_pool_entries',
                'indexes': [models.Index(fields=['source', 'is_active'], name='talent_pool_source_b2e1aa_idx'), models.Index(fields=['created_at'], name='talent_pool_created_3cdef0_idx')],
            },
        ),
    ]
