# Generated by Django 6.0.6 on 2026-09-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_pool', '0003_talentpoolentry_recruit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentpoolentry',
            name='pool_type',
            field=models.CharField(choices=[('PASSIVE', '被动人才库'), ('ACTIVE', '主动人才库'), ('HIRED', '已入职人才库'), ('REJECTED', '未通过人才库'), ('BLACKLIST', '黑名单人才库'), ('GENERAL', '总人才库')], db_index=True, default='PASSIVE', max_length=16, verbose_name='子库类型'),
        ),
    ]
