# Generated by Django 6.0.6 on 2026-09-24 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtomicMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='指标名称')),
                ('source_path', models.CharField(help_text='点路径，如 candidate.age；数组用数字下标，如 candidate.workExperience.0.company', max_length=255, verbose_name='字段路径')),
                ('data_type', models.CharField(choices=[('number', '数值'), ('string', '字符串'), ('boolean', '布尔'), ('date', '日期')], default='string', max_length=16, verbose_name='数据类型')),
                ('unit', models.CharField(blank=True, default='', max_length=16, verbose_name='单位')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '原子指标',
                'verbose_name_plural': '原子指标',
                'db_table': 'metrics_atomic_metric',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DerivedMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='指标名称')),
                ('calc_func', models.CharField(help_text='派生函数注册表中的函数名，如 MAX_GAP / COUNT_IN_WINDOW / HIGHEST_EDU', max_length=64, verbose_name='计算函数')),
                ('base_path', models.CharField(help_text='计算所基于的嵌套数据路径，如 candidate.workExperience / candidate.education', max_length=255, verbose_name='数据来源路径')),
                ('params', models.JSONField(blank=True, default=dict, help_text='如 {"window_years": 5} / {"unit": "month"}', verbose_name='函数参数')),
                ('data_type', models.CharField(choices=[('number', '数值'), ('string', '字符串'), ('boolean', '布尔'), ('date', '日期')], default='number', max_length=16, verbose_name='数据类型')),
                ('unit', models.CharField(blank=True, default='', max_length=16, verbose_name='单位')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '派生指标',
                'verbose_name_plural': '派生指标',
                'db_table': 'metrics_derived_metric',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='模板名称')),
                ('operators', models.JSONField(default=list, help_text='UnifiedOperator 取值子集，如 ["GT","LT","EQ","BETWEEN"]', verbose_name='支持的运算符')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('atomic_metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='metrics.atomicmetric', verbose_name='引用原子指标')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('derived_metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='metrics.derivedmetric', verbose_name='引用派生指标')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '指标模板',
                'verbose_name_plural': '指标模板',
                'db_table': 'metrics_metric_template',
                'ordering': ['name'],
            },
        ),
    ]
