# Generated by Django 6.0.6 on 2026-09-24 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('scene', models.CharField(choices=[('TALENT_POOL', '入池'), ('FILTER', '筛选'), ('SCORING', '评分'), ('MANUAL', '手动执行')], db_index=True, default='MANUAL', max_length=16, verbose_name='应用场景')),
                ('conditions', models.JSONField(default=list, help_text='[{templateId, operator, value, meta?{min,max}}]', verbose_name='条件列表')),
                ('logic', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=8, verbose_name='条件组合逻辑')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用开关')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '指标规则',
                'verbose_name_plural': '指标规则',
                'db_table': 'metrics_metric_rule',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scene', 'enabled'], name='metrics_rule_scene_en')],
            },
        ),
    ]
