# Generated by Django 6.0.6 on 2026-09-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_metricrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricrule',
            name='blocking',
            field=models.BooleanField(default=False, help_text='开启后：该场景规则不通过时业务动作被拒绝（如拒绝入池）；关闭时仅记录结论不阻断（安全默认，避免规则误配伤业务）', verbose_name='是否阻断'),
        ),
    ]
