# Generated by Django 6.0.6 on 2026-09-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_metricrule_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricrule',
            name='blocking',
        ),
    ]
