# Generated by Django 6.0.6 on 2026-09-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_remove_metricrule_blocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicmetric',
            name='auto_generated',
            field=models.BooleanField(default=False, verbose_name='自动生成'),
        ),
        migrations.AddField(
            model_name='atomicmetric',
            name='is_enum',
            field=models.BooleanField(default=False, verbose_name='枚举型'),
        ),
    ]
