# Generated by Django 6.0.6 on 2026-10-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0014_repoint_avg_work_months_to_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrictemplate',
            name='operators',
            field=models.JSONField(default=list, help_text='UnifiedOperator 取值子集（启用算子白名单），如 ["GT","LT","EQ","BETWEEN"]', verbose_name='支持的运算符'),
        ),
        migrations.AlterField(
            model_name='metrictemplate',
            name='param_config',
            field=models.JSONField(blank=True, default=dict, help_text='{min, max, step, prefix, suffix, allOption}；离散型 step 必须为整数，连续型 step 可为任意正数', verbose_name='参数配置'),
        ),
        migrations.AlterField(
            model_name='metrictemplate',
            name='param_enums',
            field=models.JSONField(blank=True, default=list, help_text='枚举型指标的允许取值列表，如 ["本科","硕士","博士"]', verbose_name='参数枚举'),
        ),
        migrations.AlterField(
            model_name='metrictemplate',
            name='value_domain',
            field=models.JSONField(blank=True, default=dict, help_text='{segments:[{min, max, step, label}]}；分段值域，留空表示自由区间', verbose_name='值域配置'),
        ),
    ]
