# Generated by Django 6.0.6 on 2026-10-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0021_move_calc_params_to_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrictemplate',
            name='param_unit',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='参数配置单位'),
        ),
    ]
