# Generated by Django 6.0.6 on 2026-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('resource', models.CharField(db_index=True, help_text='资源类型 (Candidate/Position/...)', max_length=128)),
                ('field_key', models.CharField(help_text='字段 key (snake_case)', max_length=128)),
                ('label', models.CharField(help_text='显示名称', max_length=256)),
                ('field_type', models.CharField(choices=[('TEXT', '文本'), ('NUMBER', '数字'), ('DATE', '日期'), ('SELECT', '单选'), ('MULTISELECT', '多选'), ('BOOLEAN', '布尔')], default='TEXT', max_length=32)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, default='', max_length=512)),
                ('help_text', models.CharField(blank=True, default='', max_length=512)),
                ('default_value', models.CharField(blank=True, default='', max_length=512)),
                ('validation', models.JSONField(blank=True, default=dict, help_text='校验规则 JSON')),
                ('order_index', models.IntegerField(default=0)),
                ('group_name', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='active', max_length=32)),
                ('options', models.JSONField(blank=True, default=list, help_text='选项列表 [{value, label}]')),
            ],
            options={
                'db_table': 'dynamic_fields',
                'ordering': ['resource', 'order_index'],
                'unique_together': {('resource', 'field_key')},
            },
        ),
    ]
