# Generated by Django 6.0.6 on 2026-08-04 06:18

import nanoid.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_field', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='id',
            field=models.CharField(default=nanoid.generate.generate, editable=False, help_text='唯一标识', max_length=32, primary_key=True, serialize=False),
        ),
    ]
