# Generated by Django 6.0.6 on 2026-09-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_field', '0002_alter_dynamicfield_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, help_text='唯一标识', max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='分组 code (snake_case)', max_length=128)),
                ('name', models.CharField(help_text='分组显示名称', max_length=256)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dynamic_field_groups',
                'ordering': ['module', 'order_index'],
            },
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', '文本'), ('NUMBER', '数字'), ('DATE', '日期'), ('SELECT', '单选'), ('MULTISELECT', '多选'), ('BOOLEAN', '布尔'), ('ATTACHMENT', '附件'), ('ID_CARD', '身份证'), ('BANK_CARD', '银行卡'), ('PHONE', '手机号'), ('EMAIL', '邮箱')], default='TEXT', max_length=32),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='group',
            field=models.ForeignKey(blank=True, help_text='字段分组(可配置)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='dynamic_field.fieldgroup'),
        ),
        migrations.CreateModel(
            name='FieldModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, help_text='唯一标识', max_length=32, primary_key=True, serialize=False)),
                ('resource', models.CharField(db_index=True, help_text='资源类型 (Candidate/Position/...)', max_length=128)),
                ('code', models.CharField(help_text='模块 code (snake_case)', max_length=128)),
                ('name', models.CharField(help_text='模块显示名称', max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dynamic_field_modules',
                'ordering': ['resource', 'order_index'],
                'unique_together': {('resource', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FieldLinkageRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, help_text='唯一标识', max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='规则名称', max_length=256)),
                ('trigger_field_key', models.CharField(help_text='触发字段 key', max_length=128)),
                ('condition_op', models.CharField(choices=[('EQ', '等于'), ('NE', '不等于'), ('IN', '属于')], default='EQ', max_length=16)),
                ('condition_value', models.JSONField(blank=True, default=list, help_text='条件值(标量或数组, IN 时为数组)')),
                ('action_type', models.CharField(choices=[('SHOW', '显示'), ('HIDE', '隐藏'), ('REQUIRE', '设必填'), ('CASCADE_OPTIONS', '级联选项')], default='SHOW', max_length=32)),
                ('target_field_keys', models.JSONField(blank=True, default=list, help_text='受影响字段 key 列表')),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='级联选项映射等附加配置')),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkage_rules', to='dynamic_field.fieldmodule')),
            ],
            options={
                'db_table': 'dynamic_field_linkage_rules',
                'ordering': ['module', 'order_index'],
            },
        ),
        migrations.AddField(
            model_name='fieldgroup',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='dynamic_field.fieldmodule'),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='module',
            field=models.ForeignKey(blank=True, help_text='归属模块(可配置)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='dynamic_field.fieldmodule'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldgroup',
            unique_together={('module', 'code')},
        ),
    ]
