# Generated by Django 6.0.6 on 2026-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_field', '0003_fieldgroup_alter_dynamicfield_field_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldlinkagerule',
            name='action_config',
        ),
        migrations.RemoveField(
            model_name='fieldlinkagerule',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='fieldlinkagerule',
            name='condition_op',
        ),
        migrations.RemoveField(
            model_name='fieldlinkagerule',
            name='condition_value',
        ),
        migrations.RemoveField(
            model_name='fieldlinkagerule',
            name='target_field_keys',
        ),
        migrations.RemoveField(
            model_name='fieldlinkagerule',
            name='trigger_field_key',
        ),
        migrations.AddField(
            model_name='fieldlinkagerule',
            name='actions',
            field=models.JSONField(blank=True, default=list, help_text='动作列表 [{target_field_key, action_type, value, read_only}]'),
        ),
        migrations.AddField(
            model_name='fieldlinkagerule',
            name='condition_mode',
            field=models.CharField(choices=[('ALL', '满足以下所有条件'), ('ANY', '满足以下任一条件')], default='ALL', help_text='多条件组合方式', max_length=16),
        ),
        migrations.AddField(
            model_name='fieldlinkagerule',
            name='conditions',
            field=models.JSONField(blank=True, default=list, help_text='条件列表 [{field_key, op, value}]'),
        ),
    ]
