# Generated by Django 6.0.6 on 2026-09-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_field', '0004_remove_fieldlinkagerule_action_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', '文本'), ('NUMBER', '数字'), ('DATE', '日期'), ('SELECT', '单选'), ('MULTISELECT', '多选'), ('BOOLEAN', '布尔'), ('ATTACHMENT', '附件'), ('ID_CARD', '身份证'), ('BANK_CARD', '银行卡'), ('PHONE', '手机号'), ('EMAIL', '邮箱'), ('LIST_SINGLE', '列表单选'), ('LIST_MULTI', '列表多选')], default='TEXT', max_length=32),
        ),
    ]
