# Generated by Django 6.0.6 on 2026-09-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_field', '0005_alter_dynamicfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='confirmation_content',
            field=models.TextField(blank=True, default='', help_text='确认题-确认内容(中文)'),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='confirmation_content_en',
            field=models.TextField(blank=True, default='', help_text='确认题-确认内容(英文)'),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='confirmation_declaration',
            field=models.TextField(blank=True, default='', help_text='确认题-确认声明(中文)'),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='confirmation_declaration_en',
            field=models.TextField(blank=True, default='', help_text='确认题-确认声明(英文)'),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='label_en',
            field=models.CharField(blank=True, default='', help_text='字段名称(英文)', max_length=256),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='visibility_permission',
            field=models.CharField(choices=[('ALL_VISIBLE', '全员可见'), ('MANAGER_HIDDEN', '用人经理端不可见')], default='ALL_VISIBLE', help_text='可见权限(字段权限管理弹窗)', max_length=32),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', '文本'), ('NUMBER', '数字'), ('DATE', '日期'), ('SELECT', '单选'), ('MULTISELECT', '多选'), ('BOOLEAN', '布尔'), ('ATTACHMENT', '附件'), ('ID_CARD', '身份证'), ('BANK_CARD', '银行卡'), ('PHONE', '手机号'), ('EMAIL', '邮箱'), ('LIST_SINGLE', '列表单选'), ('LIST_MULTI', '列表多选'), ('CONFIRM', '确认题')], default='TEXT', max_length=32),
        ),
    ]
