# Generated by Django 6.0.6 on 2026-09-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_field', '0007_alter_dynamicfield_field_type_multiline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='options_source',
            field=models.JSONField(blank=True, default=dict, help_text='选项来源 {type, key}; 非空时选项由对应数据源动态解析并覆盖手动 options'),
        ),
    ]
