# Generated by Django 6.0.6 on 2026-09-15 15:18

from django.db import migrations, models


# 2026-09-15: 省/省市/省市区三类型合并为单一 REGION「行政区划」, 原精度下沉到 region_level
def migrate_region_types(apps, schema_editor):
    DynamicField = apps.get_model('dynamic_field', 'DynamicField')
    mapping = {
        'REGION_PROVINCE': 'PROVINCE',
        'REGION_PROVINCE_CITY': 'CITY',
        'REGION_PROVINCE_CITY_DISTRICT': 'DISTRICT',
    }
    for old_type, level in mapping.items():
        # 最小动作 UPDATE: 仅改写 field_type + region_level, 不动其他列
        DynamicField.objects.filter(field_type=old_type).update(
            field_type='REGION', region_level=level
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_field', '0011_dynamicfield_date_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='region_level',
            field=models.CharField(choices=[('PROVINCE', '省'), ('CITY', '省市'), ('DISTRICT', '省市区')], default='DISTRICT', help_text='行政区划层级精度(省/省市/省市区, 仅 REGION 渲染时参考)', max_length=16),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', '文本'), ('NUMBER', '数字'), ('DATE', '单点日期'), ('DATE_RANGE', '日期范围'), ('SELECT', '单选'), ('MULTISELECT', '多选'), ('BOOLEAN', '布尔'), ('ATTACHMENT', '附件'), ('ID_CARD', '身份证'), ('BANK_CARD', '银行卡'), ('PHONE', '手机号'), ('EMAIL', '邮箱'), ('LIST_SINGLE', '列表单选'), ('LIST_MULTI', '列表多选'), ('CONFIRM', '确认题'), ('MULTILINE_TEXT', '多行文本'), ('ADDRESS', '地址'), ('REGION', '行政区划')], default='TEXT', max_length=32),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='with_country',
            field=models.BooleanField(default=False, help_text='行政区划型字段是否先选国家(仅 REGION 渲染时参考)'),
        ),
        # 2026-09-15 数据迁移: 存量 REGION_* 三值合并为 REGION 并写回原精度
        migrations.RunPython(migrate_region_types, migrations.RunPython.noop),
    ]
