# Generated by Django 6.0.6 on 2026-09-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_field', '0012_dynamicfield_region_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='sub_fields',
            field=models.JSONField(blank=True, default=list, help_text='组合字段子结构 [{key,label,type,required}]; 仅 COMPOSITE 类型使用'),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', '文本'), ('NUMBER', '数字'), ('DATE', '单点日期'), ('DATE_RANGE', '日期范围'), ('SELECT', '单选'), ('MULTISELECT', '多选'), ('BOOLEAN', '布尔'), ('ATTACHMENT', '附件'), ('ID_CARD', '身份证'), ('BANK_CARD', '银行卡'), ('PHONE', '手机号'), ('EMAIL', '邮箱'), ('LIST_SINGLE', '列表单选'), ('LIST_MULTI', '列表多选'), ('CONFIRM', '确认题'), ('MULTILINE_TEXT', '多行文本'), ('ADDRESS', '地址'), ('REGION', '行政区划'), ('COMPOSITE', '组合字段')], default='TEXT', max_length=32),
        ),
    ]
