# Generated by Django 6.0.6 on 2026-09-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_field', '0013_dynamicfield_sub_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resource', models.CharField(db_index=True, help_text='资源类型 (Candidate/Position/...)', max_length=128)),
                ('entity_id', models.CharField(db_index=True, help_text='业务实体 id (如候选人 id)', max_length=32)),
                ('field_key', models.CharField(help_text='字段 key (与 DynamicField.field_key 对齐)', max_length=128)),
                ('value', models.JSONField(blank=True, null=True, verbose_name='字段值')),
            ],
            options={
                'db_table': 'dynamic_field_values',
                'ordering': ['resource', 'entity_id', 'field_key'],
                'unique_together': {('resource', 'entity_id', 'field_key')},
            },
        ),
    ]
