# Generated by Django 5.0.6 on 2026-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentpoolentry',
            name='source',
            field=models.CharField(choices=[('REJECTED', '本流程未通过'), ('WITHDRAWN', '候选人主动撤回'), ('TIMEOUT', '超时归档'), ('ACTIVE_REJECT', '主动拒绝入库'), ('MANUAL', '手动入库'), ('DIRECT_IMPORT', '直接导入（HR 上传简历）')], max_length=16, verbose_name='入库来源'),
        ),
    ]
