# Generated by Django 6.0.7 on 2026-07-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_v2_init'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'managed': False, 'verbose_name': '角色权限', 'verbose_name_plural': '角色权限'},
        ),
    ]
