# Generated by Django 6.0.6 on 2026-08-22 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hrbp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='部门HRBP'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='部门负责人2'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='分管VP'),
        ),
    ]
