# Generated by Django 6.0.6 on 2026-09-16 04:43

import apps.core.models_permission_v2
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mgmt_unit_hierarchy_and_app_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementUnitMember',
            fields=[
                ('id', models.CharField(default=apps.core.models_permission_v2.gen_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('member_type', models.CharField(choices=[('DEPT', '组织节点'), ('USER', '系统用户'), ('PERSON', 'HR台账人员')], max_length=12, verbose_name='成员类型')),
                ('department_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='组织节点ID')),
                ('user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='用户ID')),
                ('person_id', models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='HR台账人员ID')),
                ('include_children', models.SmallIntegerField(default=1, verbose_name='含子级(1是 0否)')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态(1启用 0禁用)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.managementunit', verbose_name='管理单元')),
            ],
            options={
                'verbose_name': '管理单元成员',
                'verbose_name_plural': '管理单元成员',
                'db_table': 'management_unit_members',
                'indexes': [models.Index(fields=['unit'], name='idx_mum_unit'), models.Index(fields=['department_id'], name='idx_mum_dept'), models.Index(fields=['user_id'], name='idx_mum_user')],
            },
        ),
    ]
