# Generated by Django 6.0.6 on 2026-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_management_unit_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('INTERNAL', '内部员工'), ('EXTERNAL', '外部用户')], db_index=True, default='INTERNAL', max_length=20, verbose_name='用户类型'),
        ),
    ]
