# Generated by Django 6.0.6 on 2026-09-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementunit',
            name='personnel_scope',
        ),
    ]
