# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.notification.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.notification.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='如 offer.sent / interview.scheduled / stage.advanced', max_length=100, unique=True, verbose_name='模板编码')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('event', models.CharField(db_index=True, max_length=100, verbose_name='触发事件')),
                ('templates', models.JSONField(default=dict, help_text='{"IN_APP": "...", "EMAIL": {"subject": "...", "body": "..."}, "SMS": "...", "WECOM": "..."}', verbose_name='多通道模板')),
                ('variables', models.JSONField(default=list, help_text='[{"name": "candidate_name", "type": "string", "required": true, "example": "张三"}]', verbose_name='可用变量')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.notification.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('IN_APP', '站内信'), ('EMAIL', '邮件'), ('SMS', '短信'), ('WECOM', '企微')], max_length=16, verbose_name='通道')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容')),
                ('event', models.CharField(db_index=True, max_length=100, verbose_name='事件')),
                ('context', models.JSONField(default=dict, verbose_name='上下文')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='已读时间')),
                ('failed_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notification.notificationtemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '通知日志',
                'verbose_name_plural': '通知日志',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_0ec9b5_idx'), models.Index(fields=['event', 'created_at'], name='notificatio_event_ac3d44_idx')],
            },
        ),
    ]
