# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.position.models
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.position.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='职位编号')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='职位名称')),
                ('description', models.TextField(blank=True, verbose_name='职位描述')),
                ('requirements', models.TextField(blank=True, verbose_name='任职要求')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='职级')),
                ('position_title', models.CharField(blank=True, max_length=100, verbose_name='职务')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='工作地点')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪资下限')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪资上限')),
                ('headcount', models.IntegerField(default=1, verbose_name='招聘人数')),
                ('filled_count', models.IntegerField(default=0, verbose_name='已招人数')),
                ('process_version', models.CharField(default='1.0', max_length=20, verbose_name='流程版本')),
                ('state', django_fsm.FSMField(db_index=True, default='DRAFT', max_length=50, protected=True, verbose_name='职位状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('assistants', models.ManyToManyField(blank=True, related_name='assisted_positions', to=settings.AUTH_USER_MODEL, verbose_name='职位协助人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='core.department', verbose_name='所属部门')),
                ('hiring_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_manager_positions', to=settings.AUTH_USER_MODEL, verbose_name='用人经理')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_positions', to=settings.AUTH_USER_MODEL, verbose_name='职位负责人')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='process.recruitmentprocess', verbose_name='使用的流程')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'db_table': 'positions',
                'indexes': [models.Index(fields=['department', 'state'], name='positions_departm_d79943_idx'), models.Index(fields=['hiring_manager', 'state'], name='positions_hiring__0d0ac0_idx')],
            },
        ),
    ]
