# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.time_limit.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLimitRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.time_limit.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('process_id', models.CharField(db_index=True, max_length=32, verbose_name='流程ID')),
                ('workflow_version', models.CharField(max_length=20, verbose_name='流程版本')),
                ('rule_name', models.CharField(max_length=30, verbose_name='规则名称')),
                ('conditions', models.JSONField(default=list, help_text='JSON 数组', verbose_name='执行条件')),
                ('lock_duration', models.IntegerField(help_text='1-365 天', verbose_name='锁定时长（自然日）')),
                ('extension_per_person', models.IntegerField(default=0, help_text='0-30 天', verbose_name='加时规则（天/人）')),
                ('effective_scope', models.CharField(default='NEW_ONLY', help_text='ALL / NEW_ONLY', max_length=16, verbose_name='生效方式')),
                ('priority', models.IntegerField(db_index=True, default=0, verbose_name='优先级（列表顺序）')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_limit_rules', to='process.processstagelink', verbose_name='流程-阶段关联')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '阶段限时规则',
                'verbose_name_plural': '阶段限时规则',
                'db_table': 'stage_time_limit_rules',
                'ordering': ['link', 'priority'],
            },
        ),
    ]
