# Generated by Django 6.0.6 on 2026-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(editable=False, help_text='唯一标识', max_length=32, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', help_text='雇主 / 公司名称', max_length=255)),
                ('brand_slogan', models.CharField(blank=True, default='', help_text='品牌标语 / Slogan', max_length=255)),
                ('brand_intro', models.TextField(blank=True, default='', help_text='雇主品牌文案')),
                ('logo_url', models.CharField(blank=True, default='', help_text='Logo 图片 URL', max_length=512)),
                ('portal_title', models.CharField(blank=True, default='', help_text='招聘门户标题', max_length=255)),
                ('portal_subtitle', models.CharField(blank=True, default='', help_text='招聘门户副标题', max_length=255)),
                ('portal_banner_url', models.CharField(blank=True, default='', help_text='招聘门户 Banner 图 URL', max_length=512)),
                ('primary_color', models.CharField(blank=True, default='', help_text='门户主题主色 (hex)', max_length=32)),
                ('contact_email', models.CharField(blank=True, default='', help_text='招聘联系邮箱', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', help_text='招聘联系电话', max_length=64)),
                ('social_links', models.JSONField(blank=True, default=list, help_text='社交 / 官网链接列表')),
            ],
            options={
                'verbose_name': '品牌信息',
                'verbose_name_plural': '品牌信息',
                'db_table': 'brand_info',
                'ordering': ['created_at'],
            },
        ),
    ]
