# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.demand.models
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.demand.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='需求编号')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('headcount', models.IntegerField(verbose_name='需求人数')),
                ('filled_count', models.IntegerField(default=0, verbose_name='已招人数')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='职级')),
                ('position_title', models.CharField(blank=True, max_length=100, verbose_name='职务')),
                ('process_version', models.CharField(default='1.0', max_length=20, verbose_name='流程版本')),
                ('jd', models.TextField(blank=True, verbose_name='JD')),
                ('requirements', models.TextField(blank=True, verbose_name='任职要求')),
                ('state', django_fsm.FSMField(db_index=True, default='DRAFT', max_length=50, protected=True, verbose_name='需求状态')),
                ('priority', models.CharField(choices=[('P0', 'P0-高'), ('P1', 'P1-中'), ('P2', 'P2-低')], default='P1', max_length=8, verbose_name='优先级')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='core.department', verbose_name='需求部门')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_demands', to=settings.AUTH_USER_MODEL, verbose_name='负责HR')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='process.recruitmentprocess', verbose_name='招聘流程')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_demands', to=settings.AUTH_USER_MODEL, verbose_name='需求提出人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '招聘需求',
                'verbose_name_plural': '招聘需求',
                'db_table': 'demands',
            },
        ),
        migrations.CreateModel(
            name='DemandApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.demand.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('level', models.IntegerField(verbose_name='审批层级')),
                ('result', models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '通过'), ('REJECTED', '驳回')], default='PENDING', max_length=16, verbose_name='审批结果')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='demand.demand', verbose_name='需求')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '需求审批',
                'verbose_name_plural': '需求审批',
                'db_table': 'demand_approvals',
                'ordering': ['demand', 'level'],
            },
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['state', 'department'], name='demands_state_f7ef84_idx'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['hr', 'state'], name='demands_hr_id_0f82cd_idx'),
        ),
    ]
