# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.field_acl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldACL',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.field_acl.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('entity', models.CharField(db_index=True, help_text='如 candidate / offer', max_length=64, verbose_name='实体名')),
                ('field', models.CharField(db_index=True, help_text='如 phone / salary', max_length=64, verbose_name='字段名')),
                ('role_code', models.CharField(db_index=True, max_length=50, verbose_name='角色编码')),
                ('permission', models.CharField(choices=[('READ', '可读'), ('MASK', '脱敏可见'), ('NONE', '不可见')], max_length=8, verbose_name='权限')),
            ],
            options={
                'verbose_name': '字段级 ACL',
                'verbose_name_plural': '字段级 ACL',
                'db_table': 'field_acls',
                'unique_together': {('entity', 'field', 'role_code')},
            },
        ),
    ]
