# Generated by Django 6.0.6 on 2026-09-14 16:16

import apps.field_acl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_acl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAclAccessLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.field_acl.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('entity', models.CharField(db_index=True, max_length=64, verbose_name='实体名')),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='用户名')),
                ('role_codes', models.JSONField(default=list, verbose_name='访问时角色')),
                ('masked_fields', models.JSONField(default=list, verbose_name='脱敏字段')),
                ('hidden_fields', models.JSONField(default=list, verbose_name='隐藏字段')),
                ('request_path', models.CharField(blank=True, default='', max_length=255, verbose_name='请求路径')),
                ('client_ip', models.CharField(blank=True, default='', max_length=64, verbose_name='客户端IP')),
            ],
            options={
                'verbose_name': '字段级访问审计',
                'verbose_name_plural': '字段级访问审计',
                'db_table': 'field_acl_access_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
