# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.integration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.integration.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MOKA', '摩卡 HRIS'), ('EMAIL', '邮件服务'), ('WECOM', '企业微信'), ('SMS', '短信服务'), ('BACKGROUND_CHECK', '背调服务'), ('PORTAL', '招聘门户')], max_length=32, unique=True, verbose_name='类型')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('config', models.JSONField(default=dict, help_text='API URL, Key 等敏感配置', verbose_name='配置')),
                ('field_mapping', models.JSONField(default=dict, verbose_name='字段映射')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
            ],
            options={
                'verbose_name': '集成配置',
                'verbose_name_plural': '集成配置',
                'db_table': 'integration_configs',
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.integration.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(help_text='USER_PULL/USER_PUSH/RESUME_PUSH/...', max_length=32, verbose_name='同步类型')),
                ('status', models.CharField(help_text='SUCCESS/PARTIAL/FAILED', max_length=16, verbose_name='状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='总数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integration.integrationconfig', verbose_name='配置')),
            ],
            options={
                'verbose_name': '集成同步日志',
                'verbose_name_plural': '集成同步日志',
                'db_table': 'integration_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
