# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.audit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.audit.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('READ', '读取（敏感字段）'), ('EXPORT', '导出'), ('LOGIN', '登录'), ('LOGOUT', '登出'), ('PERMISSION_DENIED', '权限拒绝')], db_index=True, max_length=20, verbose_name='操作类型')),
                ('entity', models.CharField(db_index=True, max_length=64, verbose_name='实体名')),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='实体ID')),
                ('field', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='字段名')),
                ('old_value', models.TextField(blank=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, verbose_name='新值')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_id', models.CharField(blank=True, max_length=32, verbose_name='Request ID')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
