# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.channel.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='渠道名')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='渠道编码')),
                ('category', models.CharField(help_text='CAMPUS/SOCIAL/HEADHUNTER/REFERRAL/AGENCY/OTHER', max_length=50, verbose_name='渠道分类')),
                ('cost_per_resume', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单简历成本')),
                ('cost_per_hire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单入职成本')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总投入')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '招聘渠道',
                'verbose_name_plural': '招聘渠道',
                'db_table': 'channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelCost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.channel.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('cost_type', models.CharField(help_text='POSTER/BOOTH/AGENT_FEE/OTHER', max_length=32, verbose_name='费用类型')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('incurred_at', models.DateField(verbose_name='发生日期')),
            ],
            options={
                'verbose_name': '渠道成本',
                'verbose_name_plural': '渠道成本',
                'db_table': 'channel_costs',
                'ordering': ['-incurred_at'],
            },
        ),
    ]
