# Generated by Django 6.0.6 on 2026-09-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reason_library', '0008_add_max_selectable_tags'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rulesceneassignment',
            name='uniq_scene',
        ),
        migrations.AddField(
            model_name='rulesceneassignment',
            name='recruit_type',
            field=models.CharField(choices=[('social', 'social'), ('campus', 'campus')], db_index=True, default='social', max_length=16, verbose_name='招聘类型'),
        ),
        migrations.AddConstraint(
            model_name='rulesceneassignment',
            constraint=models.UniqueConstraint(fields=('scene', 'recruit_type'), name='uniq_scene_type'),
        ),
    ]
