# Generated by Django 6.0.6 on 2026-10-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reason_library', '0015_scenerule_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneruleversion',
            name='change_kind',
            field=models.CharField(help_text='create / update / rollback / import', max_length=16, verbose_name='变更类型'),
        ),
    ]
