# Generated by Django 6.0.6 on 2026-07-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentstage',
            name='is_end',
            field=models.BooleanField(db_index=True, default=False, verbose_name='结束阶段'),
        ),
        migrations.AddField(
            model_name='recruitmentstage',
            name='is_start',
            field=models.BooleanField(db_index=True, default=False, verbose_name='起始阶段'),
        ),
    ]
