# Generated by Django 6.0.6 on 2026-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_stage_start_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerule',
            name='auto_advance_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='延迟天数 (DELAYED 时使用)'),
        ),
        migrations.AddField(
            model_name='stagerule',
            name='auto_advance_timing',
            field=models.CharField(blank=True, default='NONE', help_text='NONE / IMMEDIATE / DELAYED', max_length=32, verbose_name='自动流转触发时机'),
        ),
        migrations.AddField(
            model_name='stagerule',
            name='auto_advance_type',
            field=models.CharField(blank=True, default='NONE', help_text='NONE / MEET_NEXT / IGNORE_NEXT / MEET_NEXT_OR_N2 / N1_ALL_PASS', max_length=32, verbose_name='自动流转类型'),
        ),
        migrations.AddField(
            model_name='stagerule',
            name='default_handler_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='默认处理人字段'),
        ),
        migrations.AddField(
            model_name='stagerule',
            name='default_handler_type',
            field=models.CharField(blank=True, default='CUSTOM', help_text='FROM_DEMAND / FROM_POSITION / CUSTOM', max_length=32, verbose_name='默认处理人类型'),
        ),
        migrations.AddField(
            model_name='stagerule',
            name='default_handler_user_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='默认处理人 user id 列表 (CUSTOM 时)'),
        ),
        migrations.AddField(
            model_name='stagerule',
            name='interview_round_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='关联面试轮次 id 列表'),
        ),
        migrations.AddField(
            model_name='stagerule',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='阶段限时 (小时)'),
        ),
        migrations.AddField(
            model_name='stagerule',
            name='time_limit_scope',
            field=models.CharField(blank=True, default='NEW_ONLY', help_text='NEW_ONLY / ALL', max_length=32, verbose_name='限时范围'),
        ),
    ]
