# Generated by Django 6.0.6 on 2026-08-04 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.process.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_alter_candidate_email_hash_and_more'),
        ('process', '0003_stagerule_auto_advance_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRecommendation',
            fields=[
                ('id', models.CharField(default=apps.process.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, verbose_name='推荐理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='推荐时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_records', to='candidate.candidate', verbose_name='候选人')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_recommendations', to='process.recruitmentprocess', verbose_name='所属流程')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='推荐人')),
            ],
            options={
                'verbose_name': '候选人推荐记录',
                'verbose_name_plural': '候选人推荐记录',
                'db_table': 'candidate_recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['process', 'candidate'], name='candidate_r_process_cac0c0_idx'), models.Index(fields=['recommender', 'created_at'], name='candidate_r_recomme_57a8bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateScreen',
            fields=[
                ('id', models.CharField(default=apps.process.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('screen_result', models.JSONField(default=dict, help_text='{decision, comment, ...}', verbose_name='筛选结果')),
                ('screened_at', models.DateTimeField(auto_now_add=True, verbose_name='筛选时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screen_records', to='candidate.candidate', verbose_name='候选人')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_screens', to='process.recruitmentprocess', verbose_name='所属流程')),
                ('screened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screen_decisions', to=settings.AUTH_USER_MODEL, verbose_name='筛选人')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_screens', to='process.recruitmentstage', verbose_name='当前阶段')),
            ],
            options={
                'verbose_name': '候选人筛选记录',
                'verbose_name_plural': '候选人筛选记录',
                'db_table': 'candidate_screens',
                'ordering': ['-screened_at'],
                'indexes': [models.Index(fields=['process', 'candidate'], name='candidate_s_process_6a5480_idx'), models.Index(fields=['screened_by', 'screened_at'], name='candidate_s_screene_624214_idx')],
            },
        ),
    ]
