# Generated by Django 6.0.6 on 2026-08-10 02:49
"""T1 — RecruitmentProcess 版本化地基。

操作顺序是**硬约束**，不得随意调整：

1. ``AlterField(code)`` 去 ``unique=True`` —— 同 code 多版本行的前提。
2. ``AddField(version_seq)``
3. ``AddField(is_latest, default=False)`` —— 存量行全部 ``False``
   → C3' 表达式全为 ``NULL`` → 第 6 步 ``AddConstraint`` 不会因存量数据失败。
4. ``AlterField(current_version)`` default ``'1.0'`` → ``'V1.0'``。
5. ``AddIndex(idx_process_code_latest)``
6. ``AddConstraint`` ×3
7. ``RunPython`` 回填 —— 每 code 只置 1 行 ``is_latest=True``，亦不冲突。

⚠️ 第 6 步的 ``uniq_process_code_current_version`` 对存量脏数据（同 code 混用
``'1.0'`` / ``'V1.0'``）会抛 ``IntegrityError`` 让 migration 变红。**这是期望行为**，
不要用 try/except 吞掉——脏数据必须在部署时立刻暴露。
"""
import re

from django.conf import settings
from django.db import migrations, models

# 干净形态：'1.0' / 'V1.0' / 'V12.3'
CLEAN_VERSION = re.compile(r'^V?\d+\.\d+$')


def normalize_current_version(raw, seq):
    """current_version → 规范化 'V{seq}.0'。任何改写都不静默：全部返回告警串。

    两类改写各自告警，不得合并、不得省略其一：

    - **干净但被改写**（``'V1.2'`` → ``'V1.0'``、``'1.0'`` → ``'V1.0'``）：值是可解析的，
      但归一到 ``V{seq}.0`` 会**丢掉 minor 位**。原实现在这一支返回 ``None``（无告警），
      于是 ``'V1.2'`` 这类人工维护过的版本号会被**静默**抹平——运维事后无从察觉。
      本支现在照样收集 warning，只是措辞区分于「污染」。
    - **污染/不可识别**（``'1.0+1'``）：无法反推真实版本，按 seq 强制归一 + 告警。
    """
    raw = raw or ''
    norm = f'V{seq}.0'
    if CLEAN_VERSION.match(raw):
        if norm != raw:
            # 干净值也可能被改写（如 'V1.2' → 'V1.0'）：minor 位丢失必须留痕，不得静默
            return norm, f'current_version={raw!r} normalized to {norm!r} (minor version dropped)'
        return norm, None
    # 已污染（'1.0+1'）或不可识别：无法反推真实版本，按 seq 强制归一，显式告警（非静默）
    return norm, f'current_version={raw!r} coerced to {norm!r} (was not clean)'


def backfill_version_fields(apps, schema_editor):
    """按 code 分组回填 version_seq / is_latest / current_version。

    ⚠️ 历史模型的 ``objects`` 是原生 Manager，**不过滤软删**——这是本仓通病。
    此处遍历全部行（含软删）给 ``version_seq`` 是**有意为之**：漏掉软删行会让它们
    保持 default=1，与同 code 的第一行撞 ``uniq_process_code_version_seq``。
    只在挑选 latest 时才用 live 集过滤。
    """
    RecruitmentProcess = apps.get_model('process', 'RecruitmentProcess')
    warnings = []
    for code in RecruitmentProcess.objects.values_list('code', flat=True).distinct():
        rows = list(RecruitmentProcess.objects.filter(code=code).order_by('created_at', 'id'))
        if not rows:
            continue
        # version_seq 按 created_at 递增赋（克隆行创建更晚 → seq 更大）；id 二次排序兜底平局
        for i, r in enumerate(rows, start=1):
            r.version_seq = i
            norm, warn = normalize_current_version(r.current_version, i)
            r.current_version = norm
            if warn:
                warnings.append((code, r.id, warn))
        # is_latest 只在 live 行里选——软删行永不为 latest，与 soft_delete() 的 is_latest=False 同一不变量
        live_rows = [r for r in rows if r.deleted_at is None]
        latest_id = live_rows[-1].id if live_rows else None
        for r in rows:
            r.is_latest = (latest_id is not None and r.id == latest_id)
        if latest_id is None:
            warnings.append((code, '-', f'code={code} 全部行已软删，该 code 无 live 最新版本（预期行为，仅记录）'))
        # bulk_update 生成单条 UPDATE ... SET is_latest = CASE WHEN id=... END：
        # 同 code 内每行只赋值一次，且回填前所有行均为 False → 不存在瞬态双 latest，不会误触发 C3'。
        RecruitmentProcess.objects.bulk_update(rows, ['version_seq', 'is_latest', 'current_version'])
    if warnings:
        # 显式输出，不静默：migrate 时打印到 stdout，供人工复核污染范围
        for code, rid, w in warnings:
            print(f'[backfill WARNING] code={code} id={rid} {w}')


def reverse_backfill(apps, schema_editor):
    """回滚：is_latest/version_seq 置默认（字段仍在，仅清语义）。

    - 此 update 把所有行 is_latest 置 False → 表达式全为 NULL → 不违反 C3'。
    - ⚠️ ``current_version`` 规范化**不可逆**：forward 把 '1.0' 重写为 'V1.0'，
      reverse 不回滚版本号（已裁定为可接受的单向点）。
    """
    RecruitmentProcess = apps.get_model('process', 'RecruitmentProcess')
    RecruitmentProcess.objects.update(is_latest=False, version_seq=1)


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_candidaterecommendation_candidatescreen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. 去 code unique —— 同 code 多版本行的前提
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='code',
            field=models.CharField(help_text='W+三位流水号', max_length=20, verbose_name='流程编号'),
        ),
        # 2. version_seq
        migrations.AddField(
            model_name='recruitmentprocess',
            name='version_seq',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='版本序号'),
        ),
        # 3. is_latest —— default=False 让存量行全部退出 C3' 表达式（贡献 NULL）
        migrations.AddField(
            model_name='recruitmentprocess',
            name='is_latest',
            field=models.BooleanField(default=False, verbose_name='是否最新版'),
        ),
        # 4. current_version default 统一为 'V1.0'
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='current_version',
            field=models.CharField(default='V1.0', help_text='如 V1.2', max_length=20, verbose_name='当前版本'),
        ),
        # 5. 复合索引：服务 filter(code=..., is_latest=True, ...) 主力查询
        migrations.AddIndex(
            model_name='recruitmentprocess',
            index=models.Index(fields=['code', 'is_latest'], name='idx_process_code_latest'),
        ),
        # 6. 三条约束
        migrations.AddConstraint(
            model_name='recruitmentprocess',
            constraint=models.UniqueConstraint(fields=('code', 'version_seq'), name='uniq_process_code_version_seq'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentprocess',
            constraint=models.UniqueConstraint(fields=('code', 'current_version'), name='uniq_process_code_current_version'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentprocess',
            constraint=models.UniqueConstraint(models.Case(models.When(is_latest=True, then=models.F('code')), default=models.Value(None)), name='uniq_one_latest_per_code', violation_error_message='同一流程线（code）只能有一个最新版本（is_latest=True）'),
        ),
        # 7. 回填
        migrations.RunPython(backfill_version_fields, reverse_backfill),
    ]
