# Generated by Django 6.0.6 on 2026-08-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_process_versioning_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentstage',
            name='stage_type',
            field=models.CharField(max_length=20, verbose_name='阶段类型'),
        ),
    ]
