# Generated by Django 6.0.6 on 2026-09-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_candidaterecommendation_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerule',
            name='archive_rules',
            field=models.JSONField(blank=True, default=list, help_text='FE 写入 archive_rules schema: [{id,name,enabled,scope,expression,items[],lock_days,extend_days,effective_scope}]', verbose_name='自动归档规则列表'),
        ),
        migrations.AddField(
            model_name='stagerule',
            name='skip_rules',
            field=models.JSONField(blank=True, default=list, help_text='FE 写入 skip_rules schema: [{id,name,enabled,scope,expression,items[],action}]', verbose_name='自动跳过规则列表'),
        ),
    ]
