# Generated by Django 6.0.6 on 2026-09-08 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.process.models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_stage_rule_skip_archive_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(default=apps.process.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='R+三位流水号', max_length=20, unique=True, verbose_name='轮次编号')),
                ('name', models.CharField(max_length=50, verbose_name='轮次名称')),
                ('evaluation_form_name', models.CharField(blank=True, max_length=100, verbose_name='面试评价表')),
                ('is_universal', models.BooleanField(default=False, db_index=True, verbose_name='通用评价表')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用')], db_index=True, default='ACTIVE', max_length=16, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '面试轮次',
                'verbose_name_plural': '面试轮次',
                'db_table': 'interview_rounds',
                'ordering': ['code'],
            },
        ),
    ]
