# Generated by Django 6.0.6 on 2026-09-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_remove_recruitment_stage_type_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentstage',
            name='stage_type',
            field=models.CharField(choices=[('START_END', '起止阶段'), ('SCREEN', '筛选型'), ('INVITATION', '邀约型'), ('INTERVIEW', '面试型'), ('ASSESSMENT', '测评型'), ('OFFER', 'offer型'), ('OTHER', '其他')], max_length=20, verbose_name='阶段类型'),
        ),
    ]
