// Naive UI 全量组件注册 plugin
// 2026-07-03: 抽出独立模块, 让 main.ts 和 vitest 都能复用, 避免测试环境组件未注册
import { create } from 'naive-ui'
import {
  NConfigProvider,
  NMessageProvider,
  NDialogProvider,
  NDialog,
  NNotificationProvider,
  NLoadingBarProvider,
  NButton,
  NCard,
  NInput,
  NInputNumber,
  NSelect,
  NCheckbox,
  NCheckboxGroup,
  NRadio,
  NRadioGroup,
  NSwitch,
  NForm,
  NFormItem,
  NFormItemRow,
  NDataTable,
  NPageHeader,
  NTag,
  NSpace,
  NDivider,
  NEmpty,
  NSpin,
  NAvatar,
  NBadge,
  NText,
  NH1, NH2, NH3, NH4, NH5, NP, NIcon,
  NLayout, NLayoutHeader, NLayoutSider, NLayoutContent,
  NMenu, NTabs, NTabPane, NDropdown,
  NModal, NDrawer, NDrawerContent,
  NPopconfirm, NPopover, NTooltip,
  NDescriptions, NDescriptionsItem,
  NTree, NTreeSelect,
  NUpload, NUploadDragger,
  NSteps, NStep,
  NGrid, NGi, NGridItem,
  NDatePicker,
  NTimeline, NTimelineItem,
  NAlert, NScrollbar,
  NCollapse, NCollapseItem,
  NBackTop, NCarousel, NCarouselItem,
  NImage, NInputGroup,
  NStatistic,
  NList, NListItem, NThing,
  NSkeleton, NResult,
  NPagination, NRadioButton,
} from 'naive-ui'

export const naivePlugin = create({
  components: [
    NConfigProvider, NMessageProvider, NDialogProvider, NNotificationProvider, NLoadingBarProvider,
    NButton, NCard, NInput, NInputNumber, NSelect,
    NCheckbox, NCheckboxGroup, NRadio, NRadioGroup, NSwitch,
    NForm, NFormItem, NFormItemRow,
    NDataTable, NTag, NSpace, NDivider, NEmpty, NSpin,
    NAvatar, NBadge, NText,
    NH1, NH2, NH3, NH4, NH5, NP, NIcon,
    NLayout, NLayoutHeader, NLayoutSider, NLayoutContent,
    NMenu, NTabs, NTabPane, NDropdown,
    NModal, NDrawer, NDrawerContent, NDialog,
    NPopconfirm, NPopover, NTooltip,
    NDescriptions, NDescriptionsItem,
    NTree, NTreeSelect,
    NUpload, NUploadDragger,
    NSteps, NStep,
    NGrid, NGi, NGridItem,
    NDatePicker,
    NTimeline, NTimelineItem,
    NAlert, NScrollbar,
    NCollapse, NCollapseItem,
    NBackTop, NCarousel, NCarouselItem,
    NImage, NInputGroup,
    NStatistic,
    NList, NListItem, NThing,
    NSkeleton, NResult,
    NPagination, NRadioButton,
  ],
})
