# Generated by Django 6.0.6 on 2026-09-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2, primary_key=True, serialize=False)),
                ('code3', models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-3', max_length=3)),
                ('name_cn', models.CharField(help_text='中文名称', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', help_text='英文名称', max_length=200)),
                ('phone_code', models.CharField(blank=True, default='', help_text='国际电话区号，如 +86', max_length=10)),
            ],
            options={
                'verbose_name': '国家/地区',
                'verbose_name_plural': '国家/地区',
                'db_table': 'code_country',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(help_text='数字代码，如 01', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='民族名称', max_length=50)),
                ('letter_code', models.CharField(blank=True, default='', help_text='罗马字母代码，如 HA', max_length=2)),
            ],
            options={
                'verbose_name': '民族',
                'verbose_name_plural': '民族',
                'db_table': 'code_ethnicity',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(help_text='ISO 639 代码', max_length=8, primary_key=True, serialize=False)),
                ('name_cn', models.CharField(help_text='中文名称', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', help_text='英文名称', max_length=200)),
            ],
            options={
                'verbose_name': '语言',
                'verbose_name_plural': '语言',
                'db_table': 'code_language',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(help_text='区划代码', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='区划名称', max_length=200)),
                ('level', models.SmallIntegerField(choices=[(1, '省级'), (2, '地级'), (3, '县级'), (4, '乡级')], db_index=True, help_text='层级 1省/2市/3县/4镇')),
                ('parent_code', models.CharField(blank=True, db_index=True, default='', help_text='上级区划代码（省级为空）', max_length=12)),
            ],
            options={
                'verbose_name': '行政区划',
                'verbose_name_plural': '行政区划',
                'db_table': 'code_region',
                'ordering': ['code'],
            },
        ),
    ]
