# Generated by Django 6.0.6 on 2026-09-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCode',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('EDUCATION', '学历'), ('JOB_CATEGORY', '职位类别'), ('RECRUIT_CHANNEL', '招聘渠道'), ('OFFBOARD_REASON', '离职原因'), ('CONTRACT_TYPE', '合同类型'), ('CURRENCY', '币种'), ('INDUSTRY', '行业')], db_index=True, help_text='业务枚举类别', max_length=40)),
                ('code', models.CharField(db_index=True, help_text='枚举值编码（同类下唯一）', max_length=64)),
                ('name', models.CharField(help_text='枚举值名称', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='说明（可选）')),
                ('parent_code', models.CharField(blank=True, db_index=True, default='', help_text='上级编码（可选层级，如行业→子行业）', max_length=64)),
                ('sort_order', models.IntegerField(default=0, help_text='排序（同类别内升序）')),
                ('is_customized', models.BooleanField(default=True, help_text='True = 用户在页面自建；标准同步项可置 False 并锁定编辑')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
            ],
            options={
                'verbose_name': '业务码表',
                'verbose_name_plural': '业务码表',
                'db_table': 'code_business',
                'ordering': ['category', 'sort_order', 'code'],
            },
        ),
    ]
