# Generated by Django 6.0.6 on 2026-09-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_table', '0002_businesscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(help_text='ISO 4217 alpha-3，如 CNY', max_length=3, primary_key=True, serialize=False)),
                ('code_numeric', models.CharField(blank=True, default='', help_text='ISO 4217 数字代码，如 156', max_length=3)),
                ('symbol', models.CharField(blank=True, default='', help_text='货币符号，如 ¥ $ €', max_length=8)),
                ('name_cn', models.CharField(help_text='中文名称', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', help_text='英文名称', max_length=200)),
            ],
            options={
                'verbose_name': '币种',
                'verbose_name_plural': '币种',
                'db_table': 'code_currency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(help_text='行业代码（门类1位/大类2位/中类3位/小类4位）', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='行业名称', max_length=200)),
                ('level', models.SmallIntegerField(choices=[(1, '门类'), (2, '大类'), (3, '中类'), (4, '小类')], db_index=True, help_text='层级 1门类/2大类/3中类/4小类')),
                ('parent_code', models.CharField(blank=True, db_index=True, default='', help_text='上级行业代码（门类为空）', max_length=8)),
            ],
            options={
                'verbose_name': '行业',
                'verbose_name_plural': '行业',
                'db_table': 'code_industry',
                'ordering': ['code'],
            },
        ),
        migrations.DeleteModel(
            name='BusinessCode',
        ),
    ]
