# Generated by Django 6.0.6 on 2026-08-04 05:45

import apps.resume_flow.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0006_alter_candidate_email_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.CharField(default=apps.resume_flow.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('resume_id', models.CharField(blank=True, db_index=True, help_text='关联的简历标识', max_length=64, verbose_name='简历ID')),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('IN_PROGRESS', '审批中'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('CANCELLED', '已取消')], db_index=True, default='PENDING', max_length=16, verbose_name='状态')),
                ('current_node_id', models.CharField(blank=True, max_length=32, verbose_name='当前节点ID')),
                ('nodes', models.JSONField(default=list, help_text='[{nodeId, role, approverId?, decidedAt?, comment?}]', verbose_name='审批节点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_flows', to='candidate.candidate', verbose_name='候选人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_approval_flows', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '审批流',
                'verbose_name_plural': '审批流',
                'db_table': 'approval_flows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalFlowHistory',
            fields=[
                ('id', models.CharField(default=apps.resume_flow.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', '创建'), ('APPROVED', '批准'), ('REJECTED', '驳回'), ('DELEGATED', '转交'), ('CANCELLED', '取消')], max_length=16, verbose_name='操作')),
                ('from_node', models.CharField(blank=True, max_length=32, verbose_name='来源节点ID')),
                ('to_node', models.CharField(blank=True, max_length=32, verbose_name='目标节点ID')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='resume_flow.approvalflow', verbose_name='审批流')),
                ('operated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_flow_histories', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审批流历史',
                'verbose_name_plural': '审批流历史',
                'db_table': 'approval_flow_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalflow',
            index=models.Index(fields=['candidate', 'status'], name='approval_fl_candida_f9a6de_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalflow',
            index=models.Index(fields=['status', 'created_at'], name='approval_fl_status_a70030_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalflowhistory',
            index=models.Index(fields=['flow', 'created_at'], name='approval_fl_flow_id_65692c_idx'),
        ),
    ]
