# Generated by Django 6.0.6 on 2026-09-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='approvalflowhistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间'),
        ),
    ]
