# Generated by Django 6.0.6 on 2026-09-23 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusAmbassador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=64, verbose_name='高校')),
                ('name', models.CharField(max_length=32, verbose_name='大使姓名')),
                ('region', models.CharField(blank=True, default='', max_length=32, verbose_name='区域')),
                ('status', models.CharField(choices=[('active', '已激活'), ('pending', '待审核'), ('inactive', '已停用')], default='pending', max_length=16, verbose_name='状态')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('recruit_type', models.CharField(choices=[('social', 'social'), ('campus', 'campus')], db_index=True, default='campus', max_length=16, verbose_name='招聘类型')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '校园大使',
                'verbose_name_plural': '校园大使',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampusModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='配置键')),
                ('config', models.JSONField(default=dict, verbose_name='配置内容')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '校招模块配置',
                'verbose_name_plural': '校招模块配置',
            },
        ),
        migrations.CreateModel(
            name='CampusSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='宣讲会名称')),
                ('school', models.CharField(blank=True, default='', max_length=64, verbose_name='高校')),
                ('session_type', models.CharField(choices=[('offline', '线下'), ('online', '线上'), ('hybrid', '线上线下结合')], default='offline', max_length=16, verbose_name='形式')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('venue', models.CharField(blank=True, default='', max_length=128, verbose_name='场地')),
                ('online_link', models.URLField(blank=True, default='', verbose_name='线上链接')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='容纳人数')),
                ('status', models.CharField(choices=[('planned', '已排期'), ('ongoing', '进行中'), ('ended', '已结束'), ('cancelled', '已取消')], default='planned', max_length=16, verbose_name='状态')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('recruit_type', models.CharField(choices=[('social', 'social'), ('campus', 'campus')], db_index=True, default='campus', max_length=16, verbose_name='招聘类型')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '宣讲会',
                'verbose_name_plural': '宣讲会',
                'ordering': ['-start_time', '-created_at'],
            },
        ),
    ]
