# Generated by Django 5.0.6 on 2026-06-16 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttask',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='请求人'),
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='生成人'),
        ),
        migrations.AddIndex(
            model_name='exporttask',
            index=models.Index(fields=['status', 'created_at'], name='export_task_status_9c0fc5_idx'),
        ),
    ]
