# Generated by Django 5.0.6 on 2026-06-16 01:10

import apps.gdpr.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPRRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default=apps.gdpr.models.gen_id, max_length=32, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('FORGET', '被遗忘权（删除）'), ('EXPORT', '数据导出'), ('RECTIFY', '数据更正')], max_length=16, verbose_name='请求类型')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('REJECTED', '已拒绝')], db_index=True, default='PENDING', max_length=16, verbose_name='状态')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('result', models.TextField(blank=True, verbose_name='处理结果')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('submitted_email', models.EmailField(blank=True, max_length=254, verbose_name='提交邮箱')),
                ('verification_code', models.CharField(blank=True, max_length=10, verbose_name='验证码')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gdpr_requests', to='candidate.candidate', verbose_name='候选人')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': 'GDPR 请求',
                'verbose_name_plural': 'GDPR 请求',
                'db_table': 'gdpr_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='gdpr_reques_status_62f86a_idx'), models.Index(fields=['candidate', 'request_type'], name='gdpr_reques_candida_0ae963_idx')],
            },
        ),
    ]
